### ISSUE TITLE
[Talk Proposal] Let's dive into "logging in Python"

### ISSUE THREAD

**Issue by akshay196** [pythonpune/meetup-talks#10]
**Title of the talk**
Let's dive into logging in Python

**Description**
In simple term, logging is a way to understand what is going on
inside an application. It can help programmer to understand flow of a
program. With logging, it is easy to constantly look at the flow that
an application going through. If error occurs, logger can provide more
insights like state of application before it arrived to the error line
than only giving trace backs.

The [logging module](https://docs.python.org/3/library/logging.html) is part of the standard Python library since version
2.3. It is described thoroughly in [PEP-282](https://www.python.org/dev/peps/pep-0282/). This session is going to
be talk cum basic tutorial that introduce about logging system in
Python.

**Prerequisites**
It is necessary that you should have Python basic knowledge. If you
are beginner, feel free to join this meet-up as there are people to
assist you if you need help in learning Python.

It is preferable that you have GNU/Linux powered laptop with Python
installed if you are wiling to get your hands dirty in Python logging
system.

And most important, hunger to learn. :smiley: 

**Keel calm and Read the logs.**

**Comment by bhavin192** [comment]
@akshay196 thank you for a detailed proposal.
This talk is scheduled in https://www.meetup.com/PythonPune/events/261809068/

**Comment by bhavin192** [comment]
#17 is merged.
