### ISSUE TITLE
Building Extensible Packages with Python

### ISSUE THREAD

**Issue by Ankit-rana** [pythonpune/meetup-talks#102]
#### Title of the talk
Coding Extensible Python Packages with Factory method Pattern and Entry Points

#### Description
Well you already know how to code a beginner project in Django or Flask But you wants to learn some skills used in Big Projects like openstack 
Here we will go through
1. Factory method pattern
2. abc metaclass's abstractmethod
3. Dynamic Imports
4. Entry points

#### Duration (including Q&A)
45 mins

#### Prerequisites
This talk is intermediate so audience should be at-least a beginner in Python 

#### Checklist
The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
Hello @Ankit-rana liked your proposal, will you be able to deliver this talk during this month's meetup which is going to be schedule on 28th June.

**Comment by Ankit-rana** [comment]
Hi @bhavin192,
I have slides but I still have to complete the code for this but 28th June should be enough for that.
Thanks

**Comment by bhavin192** [comment]
This talk has been scheduled in this month's meetup, https://www.meetup.com/PythonPune/events/271412377/
Please share the code repository and slides here once you are done (before or after the talk).

**Comment by Ankit-rana** [comment]
http://ankit-rana.github.io/blog/2020/07/11/factory-in-python
