### ISSUE TITLE
Introduction to Ansible Collection: Future of Ansible content

### ISSUE THREAD

**Issue by Akasurde** [pythonpune/meetup-talks#103]
#### Title of the talk
Introduction to Ansible Collection: Future of Ansible content

#### Description
This talk is related to Ansible collection. Ansible collection is a new feature introduced in Ansible 2.10. Collection simplifies the content delivery and management. This talk focuses introduction to Ansible Collection from scratch. 

You need to have general working knowledge related to Ansible to understand this talk.

#### Duration (including Q&A)
~35 mins + ~15mins for Q&A

#### Prerequisites
Basic working knowledge of Ansible.

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
As discussed, going to schedule this talk in this month's meetup.

**Comment by bhavin192** [comment]
This talk has been scheduled in this month's meetup, https://www.meetup.com/PythonPune/events/271412377/
Please share the code repository and or slides here once you are done (before or after the talk).
