### ISSUE TITLE
Effective and efficient use of pytest framework. 

### ISSUE THREAD

**Issue by adtandale** [pythonpune/meetup-talks#106]
#### Title of the talk
Effective and efficient use of pytest framework. 

#### Description

Attendees will get to know that how software engineers can make their life easy using pytest.

Following topics will be covered:
#########################
What is Framework.
Why pytest.
Prerequisites for pytest.
Execution of code using pytest
Some useful tricks in pytest
Different Useful pytest plugins.
Extend the boundaries of pytest
Can we integrate pytest with DevOps tools

#### Duration (including Q&A)

30-35 Mins

#### Checklist

The talk/workshop speaker agrees to,
- [x ] Share the slides, code snippets and other material used during the talk
- [ x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [ x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

#### Speaker Info

Having experience of more than 5 years in software industry.
Presented many talks in many opensource meetups like python pune, Ansible Pune,  INdian OpenStack user group, and in many colleges.
Presented talks in DevConf India, DevConf Brno, Czech republic, Europe.
Opensource contributor in many projects.
Love to share the knowledge for enthusiastic students, newcomers. 

Blog link - 
https://anandprakashtandale.wordpress.com/

**Comment by bhavin192** [comment]
As discussed offline, scheduling this talk in this month's meetup (25th July).

**Comment by bhavin192** [comment]
Hello @adtandale, can you please share slides of your talk?
