### ISSUE TITLE
Distributed system analysis made easy with PBench 

### ISSUE THREAD

**Issue by riya-17** [pythonpune/meetup-talks#107]
#### Title of the talk
Distributed system analysis made easy with PBench 

#### Description
In the current age where Performance Engineers often find themselves building distributed system solutions to  run and publish benchmark numbers, the main issue that rises is in data collection for generating the same. The incomplete or inconsistent data collected make it difficult to compare data sets effectively. Inorder to deal with the same, Red Hat performance and scale group has built a benchmarking tool which works in all environments such as bare metal, on Prem cloud, public clouds and makes it much easier to collect the required configuration along with tools data at scale. It helps maintain consistency of data during the runs and helps analysing the collected data to facilitate comparisons by a dashboard. This talk will be highlighting the use of Pbench tool to solve this hectic task of collecting data and explain  how best we utilise resources while running applications at scale. It will be beneficial for the people, who are looking for a benchmarking and performance analysis solution for their product with better consistency.

Demo run

#### Table of Contents

- About Pbench
- How Pbench resolve inconsistent data collection
- Pbench Architecture
- Components of pbench and how they interact
- Available scripts and tools
- Demo
- Visualize and analyze data in kibana
- How to contribute

#### Duration (including Q&A)
30 min

#### Prerequisites
- Python

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

#### About Speaker

Myself Riya, I am Associate Software Engineer at RedHat and a part of the Performance & Scale Engineering team. I am working on a performance benchmarking tool, Pbench. My main area of responsiblity is the the backend part of pbench for enhancing the quality and ameliorating the features. Some of my responsibilities also include conversion of code from shell script to python, bug resolving and adding new functionalities. Other than that I love exploring new places, novels, food and movies.
LinkedIn - [LinkedIn](https://www.linkedin.com/in/riya-17/)
email - riyad17031998@gmail.com

**Comment by bhavin192** [comment]
Hello @riya-17, thank you for submitting a very interesting talk. We are planning to schedule your talk during next month's meetup (August). I will update here before finalizing date of next meetup, hope that works for you.

**Comment by riya-17** [comment]
Sure

**Comment by bhavin192** [comment]
We are planning to have this month's meetup on 29th or 30th at 15:30, does that work for you?

**Comment by riya-17** [comment]
Sure @bhavin192 that works for me

**Comment by bhavin192** [comment]
This talk has been scheduled https://www.meetup.com/PythonPune/events/272520240/

@riya-17 there was a slight change in the issue template, can you please add the Table of Contents section to your proposal? Also take a look at the Speaker bio section. 
https://raw.githubusercontent.com/pythonpune/meetup-talks/master/.github/ISSUE_TEMPLATE/propose-a-talk.md

If you are on Freenode IRC, please join #pythonpune there or you can join the Telegram group here, http://tel.pythonpune.in

**Comment by riya-17** [comment]
Sure.. Will add soon

**Comment by riya-17** [comment]
@bhavin192 I have updated the info

**Comment by riya-17** [comment]
Hey @bhavin192 can we schedule a demo run to know the environment for the talk today? If possible it will be good if we can connect through some medium like LinkedIn.

**Comment by bhavin192** [comment]
Usually we do the testing an hour before, that suites best. Previously we had issues where the setup worked well a day before but not on the day of the meetup. I will send details over mail or LinkedIn. If you want to check your screensharing, mic etc, you can try it on this link, https://meet.jit.si/PythonPuneHangoutRoom

**Comment by riya-17** [comment]
Ohh ok.. Thank you.. I was unaware

**Comment by bhavin192** [comment]
No worries, we appreciate your willingness to test the setup beforehand. I have shared the details with you over email.

**Comment by visheshh** [comment]
Hi @riya-17 , Can you help me setting up pbench-server and pbench-web-server. I am not able to find any Installation guides.

**Comment by riya-17** [comment]
Hey @vishesh, 
Sure, I would love to but at present we are working to make it external user specific as we have some functionalities that are only available only internally due to which installation on public end is not properly available.
Will update you as soon as we achieve it.

Thanks a lot for your interest in Pbench
