### ISSUE TITLE
Behavior-driven development in Python/Django

### ISSUE THREAD

**Issue by devendralaulkar** [pythonpune/meetup-talks#108]
#### Title of the talk
Behavior-driven development(BDD) and testing in Python/Django

#### Description
BDD is an extension of Unit/Integration testing and TDD which involves writing test cases in a natural language that non-programmers can read which encourages collaboration between developers, QA and non-technical or business participants in a software project.

#### Table of Contents
* What is BDD?
* Need for collaboration/Why BDD
* Basics of Gherkin syntax
* Integrating behave/behave-django in your project
* Writing your first test cases
* Executing behave tests
* Pitfalls to avoid

#### Duration (including Q&A)
30 mins

#### Prerequisites
Basic understanding of Unit/Integration testing in Python.

The talk/workshop speaker agrees to,
- [x ] Share the slides, code snippets and other material used during the talk
- [ x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [ x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
Hello @devendralaulkar, thank you for showing interest in delivering a talk in our meetup. Does 25th July, 15:00 to 17:00 IST works for you?

**Comment by devendralaulkar** [comment]
25th July works for me.

Table of Contents

* What is BDD?
* Need for collaboration/Why BDD
* Basics of Gherkin syntax
* Integrating behave/behave-django in your project
* Writing your first test cases
* Executing behave tests
* Pitfalls to avoid

You can contact me at https://www.linkedin.com/in/devendralaulkar/

**Comment by bhavin192** [comment]
Hello @devendralaulkar can you please share slides and the code examples from your talk?
