### ISSUE TITLE
[Talk Proposal]  GNU Emacs - tool for all your editing needs 

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/meetup-talks#11]
**Title of the talk**  
 GNU Emacs - tool for all your editing needs 

**Description**  
We spend most of our time writing things, be it code,
documentation, blog post, emails etc. The tool that one uses to write
things should be something which is highly configurable and focuses
more on productivity. This talk will cover reasons why one should use
GNU Emacs, it will cover various things Emacs can do out of the
box. How it's possible to extend it for various programming languages
and editing needs.  

This talk will cover things like,
- Why Emacs?
- Basic navigation
- Buffers, Frames 
- Using Org mode
- Shell mode as terminal emulator
- Macros
- Calendar, Calculator, eww etc
- Extensible nature of Emacs
- Using GNU Emacs as Python IDE by @akshay196

**Prerequisites**  
If you want to try out things on your own machine, please come with a
laptop with GNU Emacs installed.

 https://www.gnu.org/software/emacs/tour/

**Comment by bhavin192** [comment]
This talk is scheduled in https://www.meetup.com/PythonPune/events/261809068/

**Comment by akshay196** [comment]
@bhavin192 Thank you for this proposal.

Elpy is an Emacs package to bring powerful Python editing to Emacs. We
will try to explain how to use Elpy to work on Python project using
Emacs.

**Prerequisites**
If possible, try for elpy installation on Emacs. You can refer [this
doc](https://elpy.readthedocs.io/en/latest/introduction.html#installation) for installation.

For any kind of query ping us on **#pythonpune** at Freenode.

**Comment by akshay196** [comment]
Here is the good tour for Emacs beginners. Hope this helps.
https://www.gnu.org/software/emacs/tour/

@bhavin192 Can you update description to have this link?

**Comment by bhavin192** [comment]
#17 is merged.
