### ISSUE TITLE
How I submitted my first Core Python patch

### ISSUE THREAD

**Issue by Akasurde** [pythonpune/meetup-talks#112]
#### Title of the talk
How I submitted my first Core Python patch

#### Description
This is 30 minutes talk that explores the process to start contributing to Python Project.

#### Table of contents
* Introduction to Open Source Contribution
* Finding problem
* Process

#### Duration (including Q&A)
30 Minutes

#### Speaker bio

My name is Abhijeet Kasurde. I am a core contributor to the Ansible repository and
maintainer of Ansible VMware and Kubernetes collection.
My GitHub id: @Akasurde
My Twitter id: @Pyro46

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
As discussed offline, we are scheduling this talk in this month's meetup. 

There were slight changes to the issue template after your proposal, can you please add the Table of contents and Speaker bio sections to this issue?
https://raw.githubusercontent.com/pythonpune/meetup-talks/master/.github/ISSUE_TEMPLATE/propose-a-talk.md

**Comment by inovizz** [comment]
Just a small note - We have total 30 mins for the talk including QnA, so @Akasurde you might want to shorten the talk to 25 mins and 5 mins of QnA. Hope that works?

cc @bhavin192

**Comment by Akasurde** [comment]
Thanks for the suggestion. I am pre-recording the session so I will be available throughout the session for QnA.

**Comment by Akasurde** [comment]
Please find the link for slides - https://github.com/Akasurde/shared_contents/blob/master/slides/contributing_to_core_python.pdf
