### ISSUE TITLE
cffi FTW - Bringing Wireshark's Dissectors to Python

### ISSUE THREAD

**Issue by gabhijit** [pythonpune/meetup-talks#113]
#### Title of the talk
`cffi` FTW - Bringing Wireshark's Dissectors to Python

#### Description

The talk is more about how to write Python extension modules using `cffi` using a motivating example and discusses practical aspects, gotchas and things to remember. I am submitting a proposal for the same for Pycon 2020 India. 

I will be talking about lessons learnt while implementing [wishpy](https://github.com/hyphenOs/wishpy). This is a WIP. 

#### Table of Contents 

Just copying from Pycon Proposal! :-) 

1. Problem definition (2-3 mins)
2. Options for developing Python bindings (2-3 mins) 
    * `cffi`
    * `ctypes`
    * `SWIG`
    * `Cython`
    * Classic Python API 
3. CFFI deep(ish) dive (10-15 mins) 
     * Working with `cffi` stages -
        - Development Stage
        - Build/Packaging Stage
        - Runtime Stage 
     * Some not so FAQs.

4. Putting things together - (5 mins)  
    * Really just a bunch of queues with Python processes/threads at the end :-) 
    * Packet visualization

#### Duration (including Q&A)

30-45 mins 

#### Prerequisites

The talk might be slightly advanced level and might need some familiarity with building C projects etc (this is not a hard requirement, but will help certainly!)

#### Speaker Info 

I have been active on and off in Python community in Pune. Thanks to other commitments don't get to attend PythonPune meetups as regularly as I'd like to, but after it's shifted to online format, I am trying to be better at at!  (though did miss  first couple of them) 

[LinkedIn Profile] https://www.linkedin.com/in/amgadgil/

#### Checklist

The talk/workshop speaker agrees to,
- [X] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [X] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by vishal-vvr** [comment]
Hello @gabhijit, thank you for submitting a very interesting talk. We are planning to schedule your talk in our this month's meetup (30th Aug 2020 at 15:30).
Please confirm you availability.
Thanks  :)

**Comment by gabhijit** [comment]
Yes - works!

**Comment by bhavin192** [comment]
There were slight changes to the issue template after your proposal, can you please add the Table of contents and Speaker bio sections to this issue?
https://raw.githubusercontent.com/pythonpune/meetup-talks/master/.github/ISSUE_TEMPLATE/propose-a-talk.md

**Comment by gabhijit** [comment]
Done!

**Comment by bhavin192** [comment]
This talk has been scheduled https://www.meetup.com/PythonPune/events/272520240/
If you are on Freenode IRC, please join #pythonpune there or you can join the Telegram group here, http://tel.pythonpune.in

**Comment by bhavin192** [comment]
Hey @gabhijit, I have shared details of tomorrow's meetup over LinkedIn.

**Comment by gabhijit** [comment]
@bhavin192 yes got them and acked there. Looks like I am the only one there at the meeting at the moment! :-)

**Comment by riya-17** [comment]
@bhavin192 I couldn't see any links for the testing. on LinkedIn as well as
mail.
