### ISSUE TITLE
Design Patterns and Python: Structural Design Patterns

### ISSUE THREAD

**Issue by aprajshekhar** [pythonpune/meetup-talks#122]
#### Title of the talk
Design Patterns and Python: Structural Design Patterns

#### Description
Structural patterns helps in creating larger application by combining multiple objects. In this talk, I will be discussing structural patterns in detail with focus on Facade and Proxy patterns

#### Table of contents

- Design Patterns: In nutshell
- Structural Patterns: Whys and wherefores
- Facade Pattern: Overview
- Implementing Facade Pattern
- Proxy Pattern: Overview
- Implementing Proxy Pattern

#### Duration (including Q&A)
45 mins to 1 hour

#### Prerequisites
Basic knowledge of python

#### Speaker bio
I am a Principal Software Engineer with Red Hat, have more than 16 years of experience in IT, having worked on applications ranging from enterprise-level web applications and game development to android applications. I am also the author of Building Dynamic Web 2.0 Websites with Ruby on Rails and .Net Framework 4.5 Expert Programming Cookbook, published by Packt Publishing. Apart from that I had also contributed to DevShed Portal on topics ranging from server-side development (JEE/.NET/RoR) to mobile (Symbian (Python)/Android-based development) and game development (SDL and OpenGL) with a total readership of more than 3 million. You can find out about my interests on my blog – http://aprajshekhar.wordpress.com. My twitter handle is @aprajshekhar.

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
Hello @aprajshekhar, sorry for not having any updates on the proposal, most of us were busy with PyCon India 2020 last month. 
Will you be able to deliver this talk during this month's meetup (31st October, I will update timing in few days).

**Comment by aprajshekhar** [comment]
@bhavin192, no worries. It would be great if it could be scheduled for next month.

**Comment by bhavin192** [comment]
Hello, will you be able to deliver this talk on 28th of this month (November)? We are planning to have the meetup around 11:00 AM to 13:00 PM IST.

**Comment by aprajshekhar** [comment]
Hi, yes I will be able to deliver this talk on 28th November. I apologize for the delay in responding.

**Comment by aprajshekhar** [comment]
- Presentation for first talk: https://drive.google.com/file/d/1A7JoIbPWxWKWn_3lx05R9M5zFNuLAUyU/view?usp=sharing
- Presentation for this talk: https://drive.google.com/file/d/11IzsTSiMQiyb-1XL7HSlMFz-qwKz0N2T/view?usp=sharing
- Martin Fowler's blog: https://martinfowler.com/
- Martin Fowler's twitter handle: https://twitter.com/martinfowler
