### ISSUE TITLE
What's new in Python 3.9

### ISSUE THREAD

**Issue by amolkahat** [pythonpune/meetup-talks#125]
#### Title of the talk
What's new in Python3.9

#### Description
The talk is about new features in Python 3.9.

#### Duration (including Q&A)
30 mins

#### Prerequisites
Basic understanding of Python.

#### Speaker bio
Full time Python developer, having 4+ years of experience in Python programming. 

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
Hello @amolkahat can you please share your slides / notes you used for this talk?
