### ISSUE TITLE
[Talk Proposal] Web app to control my AC over the internet

### ISSUE THREAD

**Issue by ChaitMat** [pythonpune/meetup-talks#13]
I would like to give an overview of the raspberry pi project I am working on which is a web app that I use to control the air conditioner in my room. I would like to talk about the following:-
- Flask, the micro web framework I used to build the app
- Celery, python module to run asynchronous tasks.
- MQTT protocol and paho-MQTT module to send data to multiple devices.
I don't wish to go in the details of the code, but explain the application of the above mentioned modules in my project.
Thank you.
Chaitanya Mathkar

**Comment by raukadah** [comment]
@bhavin192 @vishalvijayraghavan @digitronik @akshay196 Is it possible to include in this meetup?

**Comment by bhavin192** [comment]
Hey @ChaitMat, thank for sending the talk proposal. Will it be possible for you to deliver this in tomorrow's meetup that is 8th June?

**Comment by ChaitMat** [comment]
Yes it is possible. I will not take more than 15mins to deliver the talk.

**Comment by bhavin192** [comment]
Great! I will add your talk to meetup description.

**Comment by raukadah** [comment]
@bhavin192 What is the next step here?

**Comment by bhavin192** [comment]
@ChaitMat can you please share slides of you talk?

**Comment by ChaitMat** [comment]
I will share it tomorrow with the complete code.

**Comment by ChaitMat** [comment]
Please find the repository of the project here: [https://github.com/ChaitMat/my_room_environment_control](https://github.com/ChaitMat/my_room_environment_control)
Link to the presentation [here](https://docs.google.com/presentation/d/1q0qw2O6a-XGQaC2bJTWJJGZb-Y2YTlUi307I75EcJnY/edit?usp=sharing)
