### ISSUE TITLE
Memory Management in Python

### ISSUE THREAD

**Issue by GoelJatin** [pythonpune/meetup-talks#135]
#### Title of the talk
Memory Management in Python

#### Description
We'll be talking about how objects are stored in stored in memory and how they're garbage collected.

1. Reference count
1. Garbage collection
1. Generational garbage collection
1. Some gotchas
1. And then finally, some quick optimisations you can do in your Python code

#### Duration (including Q&A)
45 minutes

#### Prerequisites
Nothing specific, but having some basic knowledge of Python would be helpful.

#### Speaker bio
Jatin comes with a total of 5+ years of industry experience working on a variety of products ranging from Tools and Automation, Cloud Services, REST APIs, Programmatic Advertising and currently working on integrating Google and Microsoft OAuth solutions for secure access with on-premise products, where most part of the journey has been along the lines of Core Python and Standard Library
He is currently working with Spiceworks as Software Engineer II. You can find him on Twitter [@_JatinGoel](https://twitter.com/_JatinGoel)
Email: jatingoel1037@gmail.com

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [X] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [X] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by vishalvvr** [comment]
Hello @GoelJatin, 
Thank you for submitting the talk.
Will you be able to deliver this talk on 19th of this month (December)? 
We are planning to have the meetup around 11:00 AM to 01:00 PM IST.

**Comment by GoelJatin** [comment]
Hey @vishalvvr , there are some other plans for 19th, but I'll confirm and get back to you on this ASAP

**Comment by GoelJatin** [comment]
Hey @vishalvvr , really sorry about the delay from my end. I can give the talk this Saturday, December 19, but would be great if I can have the first slot. Thanks for your patience and understanding!!

**Comment by bhavin192** [comment]
Hey @GoelJatin sorry for not responding on this issue, we have scheduled your talk in the first slot. 
https://www.meetup.com/PythonPune/events/274919127/

We will be starting with your talk around 11:10, please join around 10:45. Hope the timing of 11:10 works for you.

https://meet.jit.si/PythonPuneDecember2020

**Comment by GoelJatin** [comment]
Slides links - https://bit.ly/jatin-pycon-memory-mgmt
