### ISSUE TITLE
Context Managers : Manage your resources smartly

### ISSUE THREAD

**Issue by Pradhvan** [pythonpune/meetup-talks#139]
#### Title of the talk
Context Managers: Manage your resources smartly

#### Description
_Rough Description:_

_What are context managers? How do they work?  What it's got to do with the `with` statement. How can I leverage them to manage resources/files effectively?  Can I write my own?_ 

_If you had ever wondered about any of those questions, this talk would try answer all of them._

#### Table of contents

* What are Context Managers ? and Why do they even exist?
* Perks of using a Context Manager?
* How does a Context Manager work?
* Writing your own Context Manager?
* Somewhat real-world examples of Context Managers
* Decorator based Context Manager with contextlib
* Handling exceptions on Decorator based Context Manager
* PyRandom: Random things I found interesting while working with Context Manager 

[Link To Slides](http://bit.ly/ContextManagersSlides)

#### Target Audience

* Beginners - Intermediate

#### Duration (including Q&A)
* Total Talk duration: ~25 Min (20 min talk + 5 min Q&A)

#### Prerequisites

* Basic understanding of Python

#### Speaker bio

Pythonista who loves all things web. Currently, writing and fixing bugs at ScrollStack.

[Wesbite](https://pradhvanbisht.in/) | [Twitter](https://twitter.com/BishtPradhvan)

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
This talk has been scheduled in this month's meetup, https://www.meetup.com/PythonPune/events/275599702/

Jitsi link: https://meet.jit.si/PythonPuneJanuary2021
Please join around 10:40, we will start around 11:10 or so.

**Comment by Pradhvan** [comment]
Follow up blogpost on the talk: https://pradhvan.scrollstack.com/post/2771/Context-Managers-in-Python 

Closing the issue now. 😄

**Comment by bhavin192** [comment]
Reopening, we are yet to create summary page and video, https://github.com/pythonpune/meetup-talks#submit-a-talkworkshop

**Comment by Pradhvan** [comment]
ah! okay, My bad! 😄
