### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by digitronik** [pythonpune/meetup-talks#140]
#### Title of the talk
GitHub Actions

#### Description
Are you maintaining/contributing to any python package? Like to automate workflows? Let's discuss common workflows for python projects (demo). If time permits, we will discuss how to use GitHub actions for writing simple bots.

#### Duration (including Q&A)
40 min

#### Prerequisites
Basic understanding of Python Package CI/CD.

#### Speaker bio
https://github.com/digitronik

#### Checklist

The talk/workshop speaker agrees to,
- [ x] Share the slides, code snippets and other material used during the talk
- [ x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [ x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
This talk has been scheduled in this month's meetup, https://www.meetup.com/PythonPune/events/276509512/

Jitsi link: https://meet.jit.si/PythonPuneFebruary2021
Please join around 10:40, we will start around 11:10 or so.

**Comment by digitronik** [comment]
https://github.com/digitronik/test-gh-action

**Comment by bhavin192** [comment]
- https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
- https://github.com/marketplace?type=actions
- https://github.com/nektos/act
