### ISSUE TITLE
Enable pythonpune github org git activity on IRC

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#15]
Since all the work related to pythonpune is done on GitHub and currently communication is handled on #pythonpune IRC channel on Freenode server.

We need to enable github irc bot notification for following activities:
* When a pull request is made:
   * Any reviewers comments on that
   * CI check passes 
   * New patchset updated
   * Finally the review merges

* When a new issue gets created:
   * Auto add labels based if it is a talk proposal or newsletter issue and confirm the same on irc
   * When someone comments on issue
   * When the issues closes.

**Comment by raukadah** [comment]
@amolkahat @digitronik Have a look on this and feel free to edit it.

**Comment by digitronik** [comment]
I started one Project which will cover things like
- Plug-able architecture single bot for all things
- GH actions
- Karma
-  Bugzilla events
- etc...

**Comment by digitronik** [comment]
Next step is to push new talk proposal to IRC.
I will push this soon.

**Comment by akshay196** [comment]
@raukadah I am not against the notification messages on IRC but we have to make sure that #pythonpune channel does not spam with lot of notifications. Only the valuable messages to organizers as well as members should be push to IRC. What do you think on this?

@vishal-vvr @bhavin192 @girish946

**Comment by bhavin192** [comment]
This is what I wanted to discuss before going forward too. Thank you @akshay196 for bringing it up here. 
Few questions which might help us come to a conclusion.

### Newsletter comments
1. Who is the intended audience / recipient for these notifications? 
    Everyone from the group / channel? If so, won't that be redundant to have same links in the newsletter? 
    That brings us to next question
2. What is the purpose of these notifications?
    Should people read the links from the channel or the newsletter?  What they are supposed to do with these notifications?

AFAIK we are not doing any kind of filtering based on up / down votes on the links.

### Talk proposals
1. Who is the intended audience / recipient for these notifications? 
    Does every talk proposal is of interest to everyone from the channel? Do other group members read all the proposals / are they required to / do they want to?
2. What is the purpose of these notification?
    Same, what to do with that link? How that helps to read unconfirmed talk proposals?

Point to note, when this issue was created, we were very few people in the channel (mostly organizers). The talk proposal notification might have made sense (though one can simply, watch the repository to get notified). Right now we have more number of people in the channel with different platforms being bridged. It will be better if we don't spam the channel with bots talking. People might start ignoring actual messages and announcements from humans :octocat:

**Comment by digitronik** [comment]
> @raukadah I am not against the notification messages on IRC but we have to make sure that #pythonpune channel does not spam with lot of notifications. Only the valuable messages to organizers as well as members should be push to IRC. What do you think on this?

@akshay +1 for this. Yup, we tried considering this. If you read the original proposal of Chandan in issue body (most of GH activity). In the last conversation on IRC/Telegram, He proposed mainly two things
- talk-proposal
- comments on newsletter issue (news contributed by our volunteers)

Now, we need to decide that this notification going to spam our communication channel or not?

My personal view it not gone span. let's take max counts
- 10 talk proposal in a month
- 30 newsletter comments
take nearly we will get 40-50 messages with this in a month. Note: Personally don't think the news on newsletter issues; collected by our people are spam(unwanted, unsolicited digital communication).

**Comment by digitronik** [comment]
> Few questions which might help us come to a conclusion.

Thanks for questions @bhavin192 
 
> ### Newsletter comments
> 1. Who is the intended audience / recipient for these notifications?

I can every interested candidate in the group who likes to know news/info collected by our contributors. 

>    Everyone from the group / channel? If so, won't that be redundant to have same links in the newsletter?

hummm this question is interesting and imp. The newsletter is a well-compiled collection of news.
Other though. Do you think everyone in a group read every message or every newsletter?
Personal view: People read messages as per the availability even some of them won't visit our newsletter/talks pages and that not a problem.

So are per me we should go with both.

> 2. What is the purpose of these notifications?
>    Should people read the links from the channel or the newsletter?  What they are supposed to do with these notifications?

isn't they have the right of it? Those people fallow chats on a group will not visit the newsletter (If they think they know all things) and some people like me will visit the newsletter to get full month Python community updates at a single page :).

Personal: I visit the newsletter to recall that link or topic which partially in my mind but forgot about it :D.

> 
> AFAIK we are not doing any kind of filtering based on up / down votes on the links.

I think we are not providing a comment link but a comment body and personally, I hate over-engineering.

> ### Talk proposals
> 1. Who is the intended audience / recipient for these notifications?

same as above.

>    Does every talk proposal is of interest to everyone from the channel? Do other group members read all the proposals / are they required to / do they want to?
The first thing; It sending the title and issue link, not the body.  Interested candidate will open the link and read the proposal.
If he/she found interesting then the forum is open (#pythonpune) :). They can add comments, search, read more about it anything.

> 2. What is the purpose of these notification?
>    Same, what to do with that link? How that helps to read unconfirmed talk proposals?
> 
> Point to note, when this issue was created, we were very few people in the channel (mostly organizers). The talk proposal notification might have made sense (though one can simply, watch the repository to get notified). Right now we have more number of people in the channel with different platforms being bridged. It will be better if we don't spam the channel with bots talking. People might start ignoring actual messages and announcements from humans :octocat:

@bhavin192 It will be our failure if only bots will talk on the channel. The bot will do their work (smartly we need to assignee it)... the main conversation depends on us.

**Comment by akshay196** [comment]
> @akshay +1 for this. Yup, we tried considering this. If you read the original proposal of Chandan in issue body (most of GH activity). In the last conversation on IRC/Telegram, He proposed mainly two things
> 
>     * talk-proposal
> 
>     * comments on newsletter issue (news contributed by our volunteers)
> 
Good to me.

> 
> Now, we need to decide that this notification going to spam our communication channel or not?
> 
> My personal view it not gone span. let's take max counts
> 
>     * 10 talk proposal in a month
> 
>     * 30 newsletter comments
>       take nearly we will get 40-50 messages with this in a month. Note: Personally don't think the news on newsletter issues; collected by our people are spam(unwanted, unsolicited digital communication).

Considering less comments on talk & newsletter issue would not spam the channel. To know if notification actually make sense on IRC/Telegram channel, we want to enable the notification. Let's enable if if there are no more discussion. However we should monitor the channel and if notification messages interrupting the channel discussion, then we should consider minimizing the notification messages.

**Comment by raukadah** [comment]
I have added this issue long time ago so that anyone can work on a standalone project where they can enable these features
for any community project.

But this thread sparkled a great discussion highlighting communication is the most important thing for a thriving community.
Thank you @akshay196, @bhavin192 and @digitronik for starting the thread. I am summarizing the questions in this comment.

* Does the telegram users are interested in notifications? (As they are the most important consumers. )
  -> We can create a poll to find that out?
* We also need to make sure people actually talk in the channel by making sure we have both way of communication
  -> Sending news links with title make sense (As people read it while accessing telegram)
     -> As number of news links goes to max 20 which will not spam the channel.But we need to monitor as @akshay196 highlighted
     -> Many people open newsletter during meetup day or later.
   -> Regarding talks topic let's discuss on call.
* I am not sure about talks links let see what users want.

**Comment by akshay196** [comment]
> Does the telegram users are interested in notifications? (As they are the most important consumers. )
> -> We can create a poll to find that out?

Good idea. Let's create a poll and go ahead as per the result.

**Comment by digitronik** [comment]
can I get some updates related to this ^^
Already we wested a lot of time without any conclusion. Currently, I'm cleaning my old PRs, let me know happy close if PR is not suitable.

**Comment by bhavin192** [comment]
@digitronik let's enable it, if someone complaints we will get back to it and tune it? (I will review your PR today, let's get the message bodies right). 

OTOH I have seen a pattern here though, people (including Chandan share the link first on IRC and then add to newsletter). Our change might help to flip this around? Like Chandan or anyone will share the link on GitHub issue which will automatically appear on IRC.
