### ISSUE TITLE
[Talk Proposal] Introduction to Jax

### ISSUE THREAD

**Issue by xennygrimmato** [pythonpune/meetup-talks#151]
#### Title of the talk: 
 Introduction to Jax

#### Description
 Jax is a new automatic differentiation library that includes compiler optimizations specific to Machine Learning tasks. It also allows for performing SPMD operations easily across multiple GPUs/TPUs. Jax is gradually becoming popular in the industry for its ease of use and simplicity.

#### Table of contents

- Automatic differentiation
- XLA
- Basics of Jax
- Jax, JIT and XLA
- Creating Neural Networks using Jax with an Example
- Case Study: Re-inforcement Learning with Jax for Deepmind's muzero
- Upcoming features: Graph Neural Networks using Jax

#### Duration (including Q&A)

20-30 minutes

#### Prerequisites

None

#### Speaker bio

- I am a Software Engineer at Google, graduated from PICT, Pune in 2016.
- https://www.linkedin.com/in/tulsyanvaibhav/

#### Checklist

The talk/workshop speaker agrees to,
- [x] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by vishalvvr** [comment]
Hello @xennygrimmato,
Thank you for submitting the talk.
Will you be able to deliver this talk on 24th of this month (24-04-2021)?
We are planning to have the meetup around 11:00 AM to 01:00 PM IST.

**Comment by xennygrimmato** [comment]
Yes, I will be able to do that.

**Comment by vishalvvr** [comment]
This talk has been scheduled in this month's meetup, https://www.meetup.com/PythonPune/events/277373781

Jitsi link: https://meet.jit.si/PythonPuneApril2021
Please join around 10:40 for testing connectivity and setup, we will start around 11:10 or so.

**Comment by bhavin192** [comment]
Hey @xennygrimmato, can you please share link to the slides, Jupyter notebook etc?

**Comment by xennygrimmato** [comment]
Hey,
Here are the links: [Slides](https://docs.google.com/presentation/d/1TAsRKvwrCreGn9-RNRIZChK9Mm6PO3uNyyzssQ02ij0/edit?usp=sharing), [Colab](https://colab.research.google.com/drive/1TnPs0qEvNQ7amCV6SUxl58dKktdwXNRP?usp=sharing)
