### ISSUE TITLE
July 2019 Python Pune Newsletter Collection Box

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#16]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during July pythonpune meetup.

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this.

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
50,000,000 Twisted Downloads Can't Be Wrong - https://atleastfornow.net/posts/py2-py3-twisted-downloads/

**Comment by raukadah** [comment]
Python for Reverse Engineering 1: ELF Binaries - https://icyphox.sh/blog/python-for-re-1/

**Comment by vishalvijayraghavan** [comment]
Python 3.8.0 beta available  - https://www.python.org/downloads/release/python-380b1/
What's new in Python 3.8 - https://docs.python.org/3.8/whatsnew/3.8.html

**Comment by sourabhdeshmukh** [comment]
How to Get the Most Out of PyCon - https://realpython.com/pycon-guide/

**Comment by raukadah** [comment]
https://laike9m.com/blog/demystifying-extended_arg,124/ - Demystifying EXTENDED_ARG

**Comment by raukadah** [comment]
Toward a “Kernel Python” - https://glyph.twistedmatrix.com/2019/06/kernel-python.html

**Comment by raukadah** [comment]
https://realpython.com/pointers-in-python/ - Pointers in Python: What's the Point?

**Comment by raukadah** [comment]
What’s happening with that pip dependency resolver? - https://pradyunsg.me/blog/2019/06/23/pip-update/

**Comment by akshay196** [comment]
Rootconf 2019 recordings are out. See sessions playlist [here](https://www.youtube.com/playlist?list=PL279M8GbNsesB7sxLO5zNbBHkOVvb7uvy)

Few recommended talks,
1. [Building reproducible Python applications for secured environments](https://www.youtube.com/watch?v=WAKk83RVtLE&list=PL279M8GbNsesB7sxLO5zNbBHkOVvb7uvy&index=26&t=0s) (~27 min)
     By Kushal Das.

**Comment by raukadah** [comment]
Python's Tale - https://www.redhat.com/en/command-line-heroes/season-3/pythons-tale

**Comment by raukadah** [comment]
Few blogs on debugging:
Debugging Python programs - https://stribny.name/blog/2019/06/debugging-python-programs
What does debugging a program look like? - https://jvns.ca/blog/2019/06/23/a-few-debugging-resources/

**Comment by sourabhdeshmukh** [comment]
Programming the cloud with Python - https://blog.pulumi.com/programming-the-cloud-with-python

**Comment by raukadah** [comment]
Building Standalone Python Applications with PyOxidizer - https://gregoryszorc.com/blog/2019/06/24/building-standalone-python-applications-with-pyoxidizer/

**Comment by raukadah** [comment]
Python Continuous Integration and Deployment From Scratch - https://semaphoreci.com/blog/python-continuous-integration-continuous-delivery

**Comment by raukadah** [comment]
Why do Python lists let you += a tuple, when you can’t + a tuple? - https://lerner.co.il/2019/06/06/why-do-python-lists-let-you-a-tuple-when-you-cant-a-tuple/

**Comment by raukadah** [comment]
Python is eating the world: How one developer's side project became the hottest programming language on the planet - https://www.techrepublic.com/article/python-is-eating-the-world-how-one-developers-side-project-became-the-hottest-programming-language-on-the-planet/
