### ISSUE TITLE
[Talk Proposal] Introduction to RabbitMQ and AMQP 0-9-1 protocol

### ISSUE THREAD

**Issue by gauravsitlani** [pythonpune/meetup-talks#165]
### Title of the talk

Introduction to RabbitMQ and AMQP 0-9-1 protocol 

### Description

AMQP 0-9-1 (Advanced Message Queuing Protocol) is a messaging protocol that enables conforming client applications to communicate with conforming messaging middleware brokers.

### Table of contents

* Introduction to AMQP 0-9-1 Model in Brief
* Overview of RabbitMQ along with some basic concepts
* Work Queues
* Publish / Subscribe Pattern
* Topic exchange

### Duration (including Q&A)

40 to 45 minutes

### Prerequisites

None

### Speaker bio

* I'm a Software Quality engineer working on Ceph storage at Red Hat.
* https://twitter.com/gauravsitlani

### The talk/workshop speaker agrees to

- [X] Share the slides, code snippets and other material used during the talk
- [x] If the talk is recorded, you grant the permission to release
the video on [PythonPune's YouTube
channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ)
under [CC-BY-4.0
license](https://creativecommons.org/licenses/by/4.0/)

- [X] Not do any hiring pitches during the talk and follow the [Code
of
Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by vishalvvr** [comment]
Hello @gauravsitlani,
will you be able to present this talk in this month's meetup? (31th Jul 2021 at 11:00 AM)

https://www.meetup.com/PythonPune/events/279560059

**Comment by gauravsitlani** [comment]
@vishalvvr sure

**Comment by gauravsitlani** [comment]
hey @vishalvvr closing this issue, since the talk was delivered and discussed in the meetup.
