### ISSUE TITLE
[lightning talk] log.today

### ISSUE THREAD

**Issue by sundeep-co-in** [pythonpune/meetup-talks#19]
**Title of the talk**

### Make contribution to your short term goals daily.

**Description**

All throughout schooling we learn to work hard preparing for exams and celebrate the results! This induces tendency to set short term goals and put some efforts achieving it. Almost every one has some method to plan and execute, what ever goals, one has. For some goals rigorous efforts are required whereas few need small but continuous inputs.

Overall if we find some balance where we keep our daily activities doing and in parallel meet goals requirements, *that certainly would be awesome*.

How about developing a tool which may keep us on track minimizing random efforts and keep ourselves more focused?

https://github.com/sundeep-co-in/makegoalsdaily

**Prerequisites**

Give it a try `$ docker pull suanand/makegoalsdaily`

**Comment by bhavin192** [comment]
Thank you for submitting the talk. Will you be able to deliver this on 13th of July? Also, can you please share duration of talk?
https://www.meetup.com/PythonPune/events/262769950/

**Comment by sundeep-co-in** [comment]
thanks for the response :+1: 

Apologies - I may not be able to deliver this on `13th July`; would request to consider in following meetups.

**Comment by raukadah** [comment]
@sundeep-co-in Will you be able to deliver this talk on 10th Aug meetup https://www.meetup.com/PythonPune/events/263413078/ ? If yes, then please share the duration of the talk?

**Comment by bhavin192** [comment]
@raukadah nope, https://flocktofedora.org/ :smile:

**Comment by sundeep-co-in** [comment]
ah, I m travelling to `flock` that time; duration would be not more than 20 mins - until we get dragged into `django`. thanks @bhavin192 maybe in September!

**Comment by bhavin192** [comment]
The talk has been scheduled in [September 2019 meetup](https://www.meetup.com/PythonPune/events/264944825/). @sundeep-co-in  See you at the venue on September 28.

**Comment by sundeep-co-in** [comment]
thanks!

**Comment by bhavin192** [comment]
Hey @sundeep-co-in can you please share your slides?

**Comment by sundeep-co-in** [comment]
Slides are [here](https://drive.google.com/file/d/1RF_p3YDBb15FD6E0fuv1QePToRGmD4vQ/view) and [here](https://youtu.be/IqMsb1ZTkBk) is the demo.

thanks!
