### ISSUE TITLE
Python for simulating Poker Games

### ISSUE THREAD

**Issue by gabhijit** [pythonpune/meetup-talks#22]
**Python for Simulating Poker Games**

This talk is about the proposal that is submitted to Pycon India 2019. We look at simulating Poker games as a way of getting started thinking in Python, that is in terms of it's built-ins core constructs and standard libraries.
[here is a link to the CFP submission](https://in.pycon.org/cfp/2019/proposals/call-raise-or-fold-python-for-simulating-poker-games~b8ymd/)

No prerequisites

**Comment by bhavin192** [comment]
Thank you for submitting the talk. Will you be able to deliver this on 13th of July? Talk duration would be around 40 to 50 minutes?
https://www.meetup.com/PythonPune/events/262769950/

**Comment by gabhijit** [comment]
Since this is a talk submitted to Pycon, I am planning to stay within 30 mins. So that it should give me a good feedback about how to timebox my talk in case my proposal gets selected for Pycon India.

**Comment by bhavin192** [comment]
This talk has been added to the meetup agenda [here]( https://www.meetup.com/PythonPune/events/262769950/).

**Comment by gabhijit** [comment]
Here's the link to the code for today's talk 

https://github.com/gabhijit/pycon/tree/master/2019/poker

**Comment by akshay196** [comment]
@gabhijit Thanks you for wonderful talk and sharing slides.
