### ISSUE TITLE
Advanced Twitter Scraping using Twint

### ISSUE THREAD

**Issue by souravsingh** [pythonpune/meetup-talks#23]
**Title**
Advanced Twitter Scraping using Twint

**Description**
When we want to scrape tweets from Twitter, we are limited by API limits. Twint is an advanced tool for scraping tweets from Twitter without any need of an API key. Twint can also do advanced scraping like scraping tweets based on a location, scraping only tweets of a verified person on a topic and many others. I hope to explore the tool in the short session.

**Prerequisites**
None

**Comment by bhavin192** [comment]
Hey @souravsingh, thank you for submitting the talk. Can we schedule this for the meetup on 13th of July?
https://www.meetup.com/PythonPune/events/262769950/

**Comment by souravsingh** [comment]
Sure

**Comment by bhavin192** [comment]
This talk has been added to the meetup agenda [here]( https://www.meetup.com/PythonPune/events/262769950/).
