### ISSUE TITLE
Exploring Graph Automation in Python

### ISSUE THREAD

**Issue by digitronik** [pythonpune/meetup-talks#25]
**Title of the talk**

Exploring Graph Automation in Python

**Description**

How do you automate graphs? How you read chart data using selenium? What are the difficulties faced while automating Graphs? these are a question which I like to cover in talk. 

**Prerequisites**

- Python selenium setup
- https://github.com/digitronik/tutorial_widgetastic

**Comment by akshay196** [comment]
@digitronik Thanks for the talk proposal. Will you be able to deliver this talk on 10th Aug meetup https://www.meetup.com/PythonPune/events/263413078/ ?
