### ISSUE TITLE
Dask distributed computing ( more power to pandas and numpy array )

### ISSUE THREAD

**Issue by satyamsoni2211** [pythonpune/meetup-talks#26]
**Title of the talk**
Dask distributed computing ( more power to pandas and numpy array )

**Description**
Parallel processing with pandas data frame and numpy array
Talking over memory issues with pandas
Improving performance measures

**Prerequisites**
Dask
Pandas
Numpy
Graphviz
Python-graphviz

**Comment by bhavin192** [comment]
Thank you for submitting the talk. Can you please share duration of talk?

**Comment by satyamsoni2211** [comment]
45 mins including demo

**Comment by akshay196** [comment]
This talk has been added to the July 2019 meetup [here](https://www.meetup.com/PythonPune/events/262769950/). Thanks @satyamsoni2211 for the proposal.

cc @bhavin192

**Comment by digitronik** [comment]
@satyamsoni2211 can you please add Jupiter notebook repo link?

**Comment by satyamsoni2211** [comment]
[Dask Jupiter Notebook Link](https://github.com/satyamsoni2211/dask-tutorial-pycon-2018)

**Comment by bhavin192** [comment]
@satyamsoni2211 can you please share link to your slides as well?
