### ISSUE TITLE
Development of web portal  to register bookings for a trekking group.

### ISSUE THREAD

**Issue by ChaitMat** [pythonpune/meetup-talks#27]
Hi guys,
My friend runs a commercial trekking group called [PHE - Pune Hiking Enthusiasts](https://www.meetup.com/PuneHikers/). People contact him and his partners to book for an event by  personally calling or messaging them. He wishes to develop a web portal where he and his partners can register the bookings and keep a track of all the bookings from multiple events.
Can you guys guide us in development of such a web portal?
Can we discuss in detail in the coming meetup?

Thanks and regards
Chaitanya

**Comment by raukadah** [comment]
Sure, feel free to drop by meetup, we can discuss.

**Comment by ChaitMat** [comment]
Thank you guys for showing me your support. I will soon create a project repository. Looking forward for your suggestions.

**Comment by raukadah** [comment]
For Django Pool tutorial follow the links below:
* Installation guide: https://docs.djangoproject.com/en/2.2/intro/install/
* Poll tutorial onward: https://docs.djangoproject.com/en/2.2/intro/tutorial01/ and move further

**Comment by digitronik** [comment]
closing this issue; I think we discussed about this in last meetup.
Thanks for discussion topic :+1:
