### ISSUE TITLE
mdcheckr travis is broken due to ppa:mike42/mdcheckr not found

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#29]
mdchecker travis ci is broken due to
```
$ sudo -E apt-add-repository -y "ppa:mike42/mdcheckr"
Cannot add PPA: 'ppa:~mike42/ubuntu/mdcheckr'.
ERROR: '~mike42' user or team does not exist.
The command "sudo -E apt-add-repository -y "ppa:mike42/mdcheckr"" failed and exited with 1 during .
Your build has been stopped.
```
Build link: https://travis-ci.org/pythonpune/meetup-talks/builds/557927092?utm_source=github_status&utm_medium=notification

**Comment by digitronik** [comment]
This is normal problem with travis ubuntu environment. I restarted build... Its working fine.

I found new bug in `mdcheckr` need some enhancements. Thanks for issue. 
I am going to work on this.
