### ISSUE TITLE
May 2019 PythonPune community news collection box

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#3]
Lots of things are happening around the Python community. Let's assemble all the news at one place. So that during the may month meetup we can publish it.

Any can contribute to it by commenting the news link in github issue comments.
Let's keep it coming!

**Comment by raukadah** [comment]
Python Used to Take Photo of Black Hole 
http://www.blog.pythonlibrary.org/2019/04/11/python-used-to-take-photo-of-black-hole/

**Comment by akshay196** [comment]
PyTexas 2019 happened on 13th and 14th April. Few talks available as follows:
- [Keynote: My Path to Becoming a Python Core Developer](https://www.pytexas.org/2019/talk/U2Vzc2lvbk5vZGU6ODU=) 
   By Emily Morehouse.
   https://www.youtube.com/watch?v=rOzUMQW4p0Y (~36 min)
- [Keynote: The Zen of Python Teams](https://www.pytexas.org/2019/talk/U2Vzc2lvbk5vZGU6MTAy)
  By Adrienne Lowe.
  https://www.youtube.com/watch?v=OmvUbHtSAaM (~27 min)

**Comment by raukadah** [comment]
https://djangochat.com/

**Comment by raukadah** [comment]
PSF 2019 Annual Report https://www.python.org/psf/annual-report/2019/

**Comment by raukadah** [comment]
https://pydist.com/  https://twitter.com/di_codes/status/1121810910887272448

**Comment by raukadah** [comment]
Raymond Hettinger - Modern solvers: Problems well-defined are problems solved - PyCon 2019 - https://www.youtube.com/watch?reload=9&v=_GP9OpZPUYc

**Comment by raukadah** [comment]
Hynek Schlawack - Maintaining a Python Project When It’s Not Your Job - PyCon 2019 - https://www.youtube.com/watch?v=9G2s1TN9QQY

**Comment by raukadah** [comment]
Automate your Python code tests with tox - https://opensource.com/article/19/5/python-tox

**Comment by digitronik** [comment]
> Automate your Python code tests with tox - https://opensource.com/article/19/5/python-tox

This is not a new thing...

**Comment by akshay196** [comment]
Kenneth Reitz, developer of `requests` is now working on [Requests 3](https://3.python-requests.org/). Check out video regarding Python development on Request 3.
https://www.youtube.com/watch?v=wRn_N034YO0

**Comment by raukadah** [comment]
Faris Chebib - Help! I'm now the leader of our Meetup group! - PyCon 2019 https://www.youtube.com/watch?v=h5YrZt788CY  https://twitter.com/siraf

**Comment by raukadah** [comment]
Replace Nested Conditional with Guard Clauses - https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html 
https://twitter.com/TalkPython/status/1126559736076341248

**Comment by raukadah** [comment]
@akshay196 @digitronik @bhavin192 @amolkahat Please vote for the links which we want to include in tomorrows newsletter.

**Comment by akshay196** [comment]
Mozilla announced [Pyodide](https://github.com/iodide-project/pyodide/) to bring the scientific Python stack in the browser. Read more about [Pyodide on Mozilla Hacks](https://hacks.mozilla.org/2019/04/pyodide-bringing-the-scientific-python-stack-to-the-browser/). Or [try it now](https://alpha.iodide.io/notebooks/300/)!

**Comment by akshay196** [comment]
Visual Studio Code announced the preview of three new extensions that enable seamless development in Containers, remotely on physical or virtual machines, and with the Windows Subsystem for Linux (WSL).

Checkout short demo videos: 
[Visual Studio Code Remote - WSL](https://youtu.be/mIHprjsSO9o)
[Visual Studio Code Remote - SSH](https://youtu.be/rh1Ag41J6IA)
[Visual Studio Code Remote - Containers](https://youtu.be/TVcoGLL6Smo)
