### ISSUE TITLE
[Travis] Some link not able check

### ISSUE THREAD

**Issue by digitronik** [pythonpune/meetup-talks#30]
https://t.me/joinchat/A3Rp5BDl9LpWMHujwZpGAw

Link how having acceptance `text/html` not checked by travis.

reference issue:
https://github.com/mike42/mdcheckr/issues/20

**Comment by bhavin192** [comment]
I'm disabling the Travis builds till we get this solved or use some other tool to test the Markdown files

**Comment by digitronik** [comment]
https://github.com/digitronik/linkstatus
