### ISSUE TITLE
Intelligence and Learning (Genetic Algorithm)

### ISSUE THREAD

**Issue by Deadshot20** [pythonpune/meetup-talks#32]
**Title of the talk**
Genetic Algorithm - GA

**Description**
The session will be focused on one type of evolutionary algorithms called GA's. We will cover the following:-

- The what/why of genetic algorithms?
- Walkthrough of the GA in detail
- Code walkthrough

> - Maximize the output of a given equation
> - Find the fastest route between two points
**Will try to cover both, if possible**

**Prerequisites**

- Familiarity with python and DS related packages like numpy, matplotlib is required.
- Curiosity to learn :blush: 

**Duration**
An interesting :sunglasses: session of about 90-100 minutes discussing and showing how real-life biological processes can be used to evolve softwares.

**Comment by digitronik** [comment]
@Deadshot20 thanks for talk-proposal :+1: please add talk duration and prerequisites.

**Comment by Deadshot20** [comment]
@digitronik I am still not sure about the duration of the talk as I am still preparing the content, but I am planning to keep it within 45-60 minutes (including session and QA). The talk proposal will be updated as soon as I finalize the content.

**Comment by raukadah** [comment]
@Deadshot20 Will you be able to deliver this talk on 10th Aug meetup https://www.meetup.com/PythonPune/events/263413078/ ? If yes, then please share the duration of the talk?

**Comment by Deadshot20** [comment]
@raukadah Yes, I will be able to deliver it on 10th Aug meetup.

**Comment by akshay196** [comment]
@Deadshot20 Let's keep talk duration to 60 minutes (including session and QA). This will have enough time for the other speakers as well. Let us know if you have any query regarding time duration.

**Comment by akshay196** [comment]
The talk has been scheduled in [August 2019 meet-up](https://www.meetup.com/PythonPune/events/263413078/). @Deadshot20 See you at the venue on August 10.

**Comment by Deadshot20** [comment]
Okay @akshay196 , I will work accordingly now. Thanks for scheduling the talk, see you on 10th. Can you please change the name from Sam Kapoor to Shaksham Kapoor (https://www.meetup.com/PythonPune/events/263413078/) :sweat_smile:

**Comment by akshay196** [comment]
> Can you please change the name from Sam Kapoor to Shaksham Kapoor

Done. :smile:

**Comment by Deadshot20** [comment]
@akshay196 A silly request, if possible can we have a whiteboard? I will be needing it!!

**Comment by akshay196** [comment]
@Deadshot20 Whiteboard is available; confirmed with venue folks.

**Comment by akshay196** [comment]
@Deadshot20 Can you please share link to your slides?

**Comment by Deadshot20** [comment]
@akshay196 Here is the PDF of the presentation.
[Genetic_Prog.pdf](https://github.com/pythonpune/meetup-talks/files/3491012/Genetic_Prog.pdf)
