### ISSUE TITLE
August 2019 Python Pune Newsletter Collection Box

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#33]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during July pythonpune meetup.

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this.

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
Monkey Patching and its consequences - https://www.pythonforthelab.com/blog/monkey-patching-and-its-consequences/

**Comment by raukadah** [comment]
The Programmer Mindset: Main Debug Loop - https://blogs.dropbox.com/tech/2019/07/the-programmer-mindset-main-debug-loop/

**Comment by raukadah** [comment]
Loop Better: a deeper look at iteration in Python - Trey Hunner  - https://treyhunner.com/2019/06/loop-better-a-deeper-look-at-iteration-in-python/

**Comment by raukadah** [comment]
@bhavin192 @digitronik @amolkahat @akshay196 Feel free to add more news to it

**Comment by amolkahat** [comment]
"Distroless" images contain only your application and its runtime dependencies. They do not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution. https://github.com/GoogleContainerTools/distroless

**Comment by amolkahat** [comment]
Loguru is a library which aims to bring enjoyable logging in Python. https://github.com/Delgan/loguru

**Comment by raukadah** [comment]
PEG Parsers - https://medium.com/@gvanrossum_83706/peg-parsers-7ed72462f97c
Building a PEG Parser - https://medium.com/@gvanrossum_83706/building-a-peg-parser-d4869b5958fb

**Comment by raukadah** [comment]
Cpython Bug Tracker: The broken promise of the Easy issue tag — My thoughts - https://medium.com/@Captain_Joannah/cpython-bug-tracker-the-broken-promise-of-the-easy-issue-tag-my-thoughts-c957c1039760

**Comment by raukadah** [comment]
Regular Instance Methods vs Class Methods vs Static Methods - https://realpython.com/lessons/regular-instance-methods-vs-class-methods-vs-static-methods/

**Comment by raukadah** [comment]
The SciPy Ecosystem Should Use Custom Entrypoints More- https://blog.danallan.com/posts/2019-07-24-use-entrypoints-more/

**Comment by raukadah** [comment]
Deep vs Shallow Copy - with Examples  - https://dev.to/laurieontech/deep-vs-shallow-copy-with-examples-cfb

**Comment by raukadah** [comment]
pandas: The two cultures - https://datapythonista.github.io/blog/pandas-the-two-cultures.html

**Comment by raukadah** [comment]
SSHPry v2 - Spy & Control SSH Connected client's TTY  - http://www.korznikov.com/2017/09/sshpry-v2-spy-control-ssh-connected.html

**Comment by raukadah** [comment]
Keynote: Python 2020 - Łukasz Langa - PyLondinium19 - https://www.youtube.com/watch?v=KDXhu4rxTNY

**Comment by raukadah** [comment]
https://github.com/snovvcrash/usbrip

**Comment by raukadah** [comment]
How to get work done in open source - http://www.gazlene.net/getting-work-done-in-open-source.html

**Comment by answerquest** [comment]
[Trio](https://github.com/python-trio/trio) : a new library (package?) showcased at a PyCon2018 for parallel / concurrent processing. Found out in this video: https://www.youtube.com/watch?v=oLkfnc_UMcE (Nathaniel J. Smith - Trio: Async concurrency for mere mortals - PyCon 2018 -PyCon 2018, 2018-05-13)

and here's the companion documentation: https://vorpus.org/blog/companion-post-for-my-pycon-2018-talk-on-async-concurrency-using-trio/

**Comment by raukadah** [comment]
PyPI now supports uploading via API token  - https://pyfound.blogspot.com/2019/07/pypi-now-supports-uploading-via-api.html

**Comment by raukadah** [comment]
Why your mock doesn’t work - https://nedbatchelder.com/blog/201908/why_your_mock_doesnt_work.html

**Comment by raukadah** [comment]
The Ultimate Guide To Memorable Tech Talks - https://medium.com/@nnja/the-ultimate-guide-to-memorable-tech-talks-e7c350778d4b

**Comment by amolkahat** [comment]
PBKDF2 + HMAC Collision explained: https://mathiasbynens.be/notes/pbkdf2-hmac

**Comment by amolkahat** [comment]
Awesome Dotfiles: https://github.com/webpro/awesome-dotfiles

**Comment by raukadah** [comment]
Loops in Python – comparison and performance - https://www.blog.duomly.com/loops-in-python-comparison-and-performance/

**Comment by answerquest** [comment]
Datasette: Turn a sqlite db into a web frontend that can be queried by the user.  
https://datasette.readthedocs.io/en/stable/installation.html#install-using-pip

**Comment by bhavin192** [comment]
This was fixed by #36
