### ISSUE TITLE
September 2019 Python Pune Newsletter Collection Box

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#38]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during July pythonpune meetup.

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this.

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by zer0ttl** [comment]
PPT from a talk I gave at the recent null meet (Pune).

### Introduction to Python asyncio for Hackers
A brief introduction the the python inbuilt module **asyncio** for hackers. Feel free to ping me in case of any questions. ([Telegram Link](https://telegram.me/zer0ttl))

PPT : [Google Drive](https://docs.google.com/presentation/d/1T1OhwqqkxfjhH8zj2wbSOhD0atDfV8yx-e8nWzmqwAs)

**Comment by mandarvaze** [comment]
I've created a cookie cutter template for (opinionated) "real world" app based on pyramid web framework

https://github.com/mandarvaze/cookiecutter-pyramid-realworld

Issues/PRs welcome.

**Comment by raukadah** [comment]
Lightweight pastebin for home network which may or may not be connected to the internet. - https://github.com/girish946/local-paste

**Comment by raukadah** [comment]
How do you verify that PyPI can be trusted? - https://snarky.ca/how-do-you-verify-pypi-can-be-trusted/

**Comment by raukadah** [comment]
Vote to promote Joannah Nanjekye as a core dev - https://discuss.python.org/t/vote-to-promote-joannah-nanjekye-as-a-core-dev/2347

**Comment by raukadah** [comment]
Coverage.py 5.0a7, and the future of pytest-cov - https://nedbatchelder.com/blog/201909/coveragepy_50a7_and_the_future_of_pytestcov.html

**Comment by raukadah** [comment]
(Almost) Never Delete a Release - https://pydist.com/blog/never-delete-a-release

**Comment by raukadah** [comment]
Sunsetting Python 2 - https://www.python.org/doc/sunset-python-2/
