### ISSUE TITLE
Hidden Secrets of Python

### ISSUE THREAD

**Issue by chaitanyarahalkar** [pythonpune/meetup-talks#44]
**Hidden Secrets of Python**

**Description**
Python has a large number of really cool modules that people don't know about. These are quite helpful. People often tend to program the hard way since they don't know about the existence of these modules. Such examples can be the itertools module, the secrets module to generate secure random numbers etc. 

**Prerequisites**

- Python 3 installed.

**Comment by bhavin192** [comment]
@chaitanyarahalkar this is interesting talk! What is expected duration of your talk? And will you be able to deliver this in September meetup which is on 28th of this month?

**Comment by chaitanyarahalkar** [comment]
The talk will be around 30 minutes. I will be available to deliver this on September 28th, 2019. Also, I would like to present this with my friend Anushka Virgaonkar. So we would like to split the talk into two parts of around 15 minutes each. Will this be okay?

Thanks

**Comment by bhavin192** [comment]
That will be awesome, can you please  also mention their GitHub username here?

**Comment by chaitanyarahalkar** [comment]
Sure it is @anushkavirgaonkar

**Comment by bhavin192** [comment]
The talk has been scheduled in [September 2019 meetup](https://www.meetup.com/PythonPune/events/264944825/). @chaitanyarahalkar @anushkavirgaonkar See you at the venue on September 28.

**Comment by bhavin192** [comment]
Hey  @chaitanyarahalkar @anushkavirgaonkar tried finding you both on meetup.com to RSVP you, but wasn't able to get the correct profiles. Can you please send an email as mentioned in the meetup description?
https://www.meetup.com/PythonPune/events/264944825/

**Comment by bhavin192** [comment]
https://github.com/pythonpune/meetup-talks/issues/49#issue-499773740
> Hey everyone,
>
>Here is the notebook that me and @anushkavirgaonkar referred during our talk today -
bit.ly/python-meetups-sept. Feel free to make a copy of this and try out the code snippets. You can comment your queries following this issue thread.
>
>Thanks,
>
>Chaitanya & Anushka
