### ISSUE TITLE
Regular Expressions - A Closer Look

### ISSUE THREAD

**Issue by deepscbe** [pythonpune/meetup-talks#45]
**Title of the talk**
Regular Expressions - A Closer Look

**Description**
Text parsing is an important aspect of data processing, but parsing huge raw files in order to extract useful data can be a pain sometimes. Yet it is a crucial part of creating structured and manageable data that can be used for further analysis

This is where regular expressions come in - often the topic of spirited debates, they are a simple and effective tool for processing data in large files.

In this talk we will discuss how regular expressions play an important role in the day-to-day tasks of a software engineer, and how much time and effort can be saved by using regular expressions and other string manipulation tools.

**Prerequisites**
Python 3 Installed
Basic knowledge about any scripting/programming language

**Comment by bhavin192** [comment]
@deepscbe that's indeed an interesting topic to talk about. Can you also share the duration of your talk? And will you be able to deliver it during September meetup which is on 28th of this month?

**Comment by deepscbe** [comment]
> @deepscbe that's indeed an interesting topic to talk about. Can you also share the duration of your talk? And will you be able to deliver it during September meetup which is on 28th of this month?

Hi Bhavin, 
Duration of the talk would be around 15-20 mins excluding QA time.
Yes, I can deliver it on September meetup.

Best Regards,
Deepa

**Comment by bhavin192** [comment]
The talk has been scheduled in [September 2019 meetup](https://www.meetup.com/PythonPune/events/264944825/). @deepscbe  See you at the venue on September 28.

**Comment by bhavin192** [comment]
Hey @deepscbe can you please share your slides?

**Comment by deepscbe** [comment]
> Hey @deepscbe can you please share your slides?

Hey, 
Yea sure. sorry for the delay in response.
Please find the slides here: [https://github.com/deepscbe/Presentations/blob/master/PythonPune_Sep_2019_Regular_Expressions.odp]
