### ISSUE TITLE
Things you can do to make your pet projects better.

### ISSUE THREAD

**Issue by girish946** [pythonpune/meetup-talks#46]
**Things that can be done to make your pet project better.**

**Description**
This will be a talk about the things I've learnt in past few years while working on my pet projects.
This talk will touch the basics of following topics with reference to a couple of my own projects.

* Dependency management.
* Writing Test cases.
* Packaging.
* Documentation.
* Continuous Integration.
* Publishing the package/project.

**Comment by bhavin192** [comment]
This talk has been scheduled https://www.meetup.com/PythonPune/events/270883519/.

**Comment by girish946** [comment]
You can find the slides at <https://girishjoshi.io/presentations/Things-that-can-be-done-to-make-your-pet-project-better/>
