### ISSUE TITLE
Hidden Secrets of Python: Supplementary Talk Notebook 

### ISSUE THREAD

**Issue by chaitanyarahalkar** [pythonpune/meetup-talks#49]
Hey everyone, 

Here is the notebook that me and @anushkavirgaonkar referred during our talk today - 
[bit.ly/python-meetups-sept](https://bit.ly/python-meetups-sept). Feel free to make a copy of this and try out the code snippets. You can comment your queries following this issue thread. 

Thanks, 

Chaitanya & Anushka

**Comment by bhavin192** [comment]
Added the comment on actual proposal https://github.com/pythonpune/meetup-talks/issues/44#issuecomment-536196724

Closing this issue.
