### ISSUE TITLE
October 2019 PythonPune Newsletter Collection Box

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#50]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during July pythonpune meetup.

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this.

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
Limit Your Try Clauses in Python - https://adamj.eu/tech/2019/10/02/limit-your-try-clauses-in-python/

**Comment by raukadah** [comment]
https://pyconf.hydpy.org/2019/

**Comment by raukadah** [comment]
My Most Used Pytest Commandline Flags - https://adamj.eu/tech/2019/10/03/my-most-used-pytest-commandline-flags/

**Comment by raukadah** [comment]
PyPy's new JSON parser - https://morepypy.blogspot.com/2019/10/pypys-new-json-parser.html via @digitronik

**Comment by raukadah** [comment]
Timsort — the fastest sorting algorithm you’ve never heard of - https://skerritt.blog/timsort-the-fastest-sorting-algorithm-youve-never-heard-of/

**Comment by raukadah** [comment]
Cool New Features in Python 3.8 - https://realpython.com/python38-new-features/

**Comment by raukadah** [comment]
Sharing Your Labor of Love: PyPI Quick and Dirty  - https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

**Comment by digitronik** [comment]
pytest important features need for dev/test
https://dev.to/martinheinz/pytest-features-that-you-need-in-your-testing-life-25cd

**Comment by raukadah** [comment]
PSF Q3 newsletter out: https://mailchi.mp/python/python-software-foundation-q3-newsletter

**Comment by sourabhdeshmukh** [comment]
https://medium.com/better-programming/meta-programming-in-python-7fb94c8c7152
by Saurabh Kukade

**Comment by sourabhdeshmukh** [comment]
https://www.youtube.com/watch?v=r-A78RgMhZU
Closing Keynote Talk - PyCon India, Chennai, October 13, 2019 (Screencast). 
In this talk, he live-code a simple stack machine and turned it into an interpreter capable of running Web Assembly.  he then use that to play a game written in Rust. 

Code written during the talk can be found at https://gist.github.com/dabeaz/7d8838b54dba5006c58a40fc28da9d5a

If you like this sort of madness and want to go more in-depth, come take a course!  https://www.dabeaz.com/courses.html

**Comment by bhavin192** [comment]
This was fixed by https://github.com/pythonpune/meetup-talks/pull/57
