### ISSUE TITLE
Introduction to GNU binutils

### ISSUE THREAD

**Issue by kamathe** [pythonpune/meetup-talks#51]
**Title of the talk**
Introduction to GNU binutils

**Description**
Imagine not having access to a software's source code but still being able to understand how the software is implemented, find vulnerabilities in it, and—better yet—fix the bugs. 
All of this in binary form. It sounds like having superpowers, doesn't it?
You too can posses such powers and GNU binutils is a good starting point to understanding and analyzing binaries.

**Prerequisites**
Basic understanding of Linux command-line tools

**Comment by bhavin192** [comment]
This is awesome @kamathe :) Can you please share the time required for this talk? Also, will you be able to deliver this talk on 19th, October?

**Comment by kamathe** [comment]
Hey @bhavin192 the duration of the talk is 30 minutes, though i won't be able to deliver this talk on 19th Oct due to some prior engagements. I would love to present this in next month's meetup.
Thanks

**Comment by bhavin192** [comment]
Hey @kamathe will you able to deliver this during this month's meetup which is on 25th January?
https://www.meetup.com/PythonPune/events/268010380/

**Comment by kamathe** [comment]
Hello @bhavin192, yes i will be able to present this talk on 25th this month
Please schedule a 30 minute slot for me, thank you

**Comment by bhavin192** [comment]
Thank you, this talk has been scheduled. https://www.meetup.com/PythonPune/events/268010380/
Please share link to your slides and or code repository if any. You can share those once you create those.

**Comment by raukadah** [comment]
@kamathe Thank you for delivering the talk, Please add the blog link so that we can include in the meetup report.

**Comment by Rohitkanyal** [comment]
Hey, Sir I am Interested in Cyber security, just check your Post 
I am Impressed by you Presentation, So Much Fascinating Work on Finding loop-hole in system. 
for Just Sake of Interest
I want to know how to get Netflix password if it is possible  !!!!!

**Comment by kamathe** [comment]
@raukadah 

https://opensource.com/article/19/10/gnu-binutils
