### ISSUE TITLE
A Very basic Python Virtual Machine which executes Python byte code.

### ISSUE THREAD

**Issue by cshintov** [pythonpune/meetup-talks#52]
In the last meetup, we had a discussion regarding Python bytecode. I hope this talk will help us to bring a little more clarity on this topic.

While learning Python I had done a project creating a toy python-virtual-machine, which takes a Python bytecode and executes it. This virtual machine only does a very small subset of operations compared to the actual implementation. It can do basic arithmetic operations and execute simple functions.

The talk will contain an explanation of the structure of the bytecode and how the VM executes it. I might need 45 mins to present the talk including Q & A.

NB: As I am leaving for vacation on 19.10.2019, Saturday, I can only present the talk on the same day morning. If the meetup is scheduled on Sunday 20.10.2019, I will have to wait for November meetup.

**Comment by bhavin192** [comment]
@cshintov very interesting talk proposal! are there any prerequisites which one should consider for this talk? Also scheduling your talk for this months meetup, as it will be on 19th October.

**Comment by cshintov** [comment]
Familiarity with python basics, stack data structure, and a high-level understanding of compilers and interpreters will be helpful.

**Comment by bhavin192** [comment]
Thank you @cshintov for your talk. Can you please share link to your slides here?

**Comment by cshintov** [comment]
Thanks for the opportunity to present the talk and to all the attendees.

You can find the slides here:
https://docs.google.com/presentation/d/1f6TF-dVIj3of5uhqFuCvgKJcfYpqpSbk9Cr8gVuAH8M/edit?usp=sharing

**Comment by bhavin192** [comment]
Hey @cshintov, do you have the code which you showed during talk uploaded somewhere?

**Comment by cshintov** [comment]
Along with the VM implementation, you can find the sample files I used for the demo and the bytecode inspection script here: 
https://github.com/cshintov/py_vm/tree/talk/python-pune

The inspect bytecode script I got from [the structure of pyc files](https://nedbatchelder.com/blog/200804/the_structure_of_pyc_files.html).
