### ISSUE TITLE
Building Serverless Microservices with Zappa

### ISSUE THREAD

**Issue by abdulwahid24** [pythonpune/meetup-talks#53]
**Building Serverless Microservices with Zappa**

**Speaker Info**
Abdulwahid Barguzar is a Software Architect and an active contributor in the open-source community. He has developed a deep understanding of architecting software product development through Python web frameworks and JavaScript frameworks. He is passionate about implementing and mastering new technologies. In his free time, he researches innovative approaches to rapidly developing and designing a software product and automation testing, aiming to become a master Software Architect.

**Description**

My objective is to showcase the practice of making python microservices as a serverless with a single line of command, It would be really helpful for Python developers who want to deploy their application just in time with a different set of deployment environments. I would cover the session with a little with hands-on which will be very enjoyable by the audience.

To justify, I would say, with my process of deploying the serverless application would eliminate the need for traditional tools like Apache, Nginx and other tools.

**Prerequisites**

- Basic understanding of the traditional deployment for Python frameworks.
- Install pipenv
- AWS account.
- Sample python application in Django/Flask/Falcon or any WSGI framework.

**Content**
Below mentioned are the content of the topic.
- Introduction
- Deployment Evolution
- Traditional Approach
- What is Serverless?
- How it helps.
- Building Serverless Microservices
- Introducing Zappa.
- Zappa evolution
- Zappa execution

[Presentation Slide](https://docs.google.com/presentation/d/1QOUbKbXEYUpyqRnYvo7JNL-F4wnnHvSpalk1DcgZjiE/edit?usp=sharing)

**Comment by bhavin192** [comment]
Thank you for the proposal @abdulwahid24. I'm going ahead and scheduling this talk in this month's meetup, which is on 19th.

**Comment by bhavin192** [comment]
@abdulwahid24 as discussed over email, you will require 30m to cover this session, right?

**Comment by abdulwahid24** [comment]
Hi Bhavin,

Yes, I will cover this in 30 minutes.

Thanks,
Abdulwahid Barguzar

**Comment by bhavin192** [comment]
Thank you for an awesome talk @abdulwahid24. Can you please share link to your slides here?

**Comment by abdulwahid24** [comment]
Thank you @bhavin192, I have updated the slide link under the presentation content section.
