### ISSUE TITLE
Functional testing using Python

### ISSUE THREAD

**Issue by son-vyas** [pythonpune/meetup-talks#55]
Functional Testing using Python

**Description**
This talk will walk through What/Why and How aspects of Functional testing. Apart from that, It would also cover the difference between Unit testing and Functional testing. 

The talk may take around 15-20 min.

**Prerequisites**
Basics of Python is more than enough

**Comment by bhavin192** [comment]
As discussed with @son-vyas offline, this talk has been scheduled in this month's meetup which is on 19th October.

**Comment by bhavin192** [comment]
Hey @son-vyas, can you please share your slides here?
