### ISSUE TITLE
November 2019 PythonPune Newsletter Collection Box

### ISSUE THREAD

**Issue by akshay196** [pythonpune/meetup-talks#58]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during November pythonpune meetup. 

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this. 

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by akshay196** [comment]
Thousands of Scientific Papers May be Invalid Due to Misunderstanding Python

Read more:
http://www.blog.pythonlibrary.org/2019/10/13/thousands-of-scientific-papers-may-be-invalid-due-to-misunderstanding-python/

**Comment by raukadah** [comment]
Thank you, Guido - https://blog.dropbox.com/topics/company/thank-you--guido

**Comment by raukadah** [comment]
What it's like to be on the Python steering council - https://snarky.ca/what-its-like-to-be-on-the-python-steering-council/

**Comment by raukadah** [comment]
Seeking Developers for Paid Contract Improving pip  - http://pyfound.blogspot.com/2019/11/seeking-developers-for-paid-contract.html

**Comment by raukadah** [comment]
Python developers survey 2019 - https://surveys.jetbrains.com/s3/c10-python-developers-survey-2019

**Comment by raukadah** [comment]
My Python Development Environment, 2020 Edition - https://jacobian.org/2019/nov/11/python-environment-2020/

**Comment by raukadah** [comment]
Coverage 5.0 beta 1 is out - https://nedbatchelder.com/blog/201911/coverage_50_beta_1.html

**Comment by raukadah** [comment]
Partial Python code formatting with Black & PyCharm - https://blog.godatadriven.com/black-formatting-selection

**Comment by raukadah** [comment]
When to switch to Python 3.8 - https://pythonspeed.com/articles/major-python-release/

**Comment by raukadah** [comment]
new #Python news site that is kind of a HackerNews clone. Check it out: https://news.python.sc/

**Comment by raukadah** [comment]
Simple text/ markdown links status checker  - https://github.com/pythonpune/linkstatus

**Comment by mandarvaze** [comment]
[Orator ORM](https://orator-orm.com/) created by same person who created [poetry](https://poetry.eustace.io/) - needs a new maintainer:

https://twitter.com/mandarvaze/status/1194264258239840267
