### ISSUE TITLE
Removing Named Entities for Legal Querying

### ISSUE THREAD

**Issue by brilliantblu** [pythonpune/meetup-talks#59]
**Title of the talk**

Removing Named Entities for Legal Querying

**Description**

It is important and difficult to find a resolved legal case that is similar to your case. In this talk, I will demonstrate the approach that I used to remove named entities from a legal query to improve the legal extraction.

**Duration (including Q&A)**

15-20 mins

**Prerequisites**

Familiarity with Natural Language Processing Pipeline will be good to have.

**Comment by raukadah** [comment]
Thanks for submitting the issue, please attach the slides link.
