### ISSUE TITLE
Machine Learning With Python using Scikit-Learn

### ISSUE THREAD

**Issue by rohit-walimbe** [pythonpune/meetup-talks#62]
**Title of the talk**
Machine Learning With Python using Scikit-Learn

**Speaker**
Rohit Walimbe ( Data Scientist, PhonePe )

**Description**
The session will cover
1- Overview of Machine Learning using Python
2- Introduction to Scikit-Learn package
3- Discuss the Scikit Learn Capabilities

- Data Preprocessing
- Dimension reduction
- Classification
- Regression
- Clustering
- Model Performance and Evaluation

4- Demo toy Machine Learning model using Scikitlearn and Jupyter Notebook
5- Supporting packages and Closing Remarks
6- Q&A

**Duration (including Q&A)**
45 Mins

**Prerequisites**
Interest in Machine Learning, Basic understanding of Stats and Maths , python version > 3.5, Jupyter Notebook for python

**Comment by bhavin192** [comment]
This talk has been scheduled here https://www.meetup.com/PythonPune/events/266249968/ 

Thank you and see you soon!

**Comment by bhavin192** [comment]
@rohit-walimbe thank you for delivering a very useful talk. 
- Can you please share link to your slides as well the demo code (if possible to upload somewhere)? 
- Is it fine if we upload the recording of your talk to our YouTube channel with CC-BY-SA 4.0 licence?

**Comment by rohit-walimbe** [comment]
HI Bhavin,

Sure. I can upload the slides. Regarding the talk upload, let me check first. Let me get back to you.

Thanks.

**Comment by rohit-walimbe** [comment]
Hi Bhavin,

Please feel free to upload the youtube talk.
I will upload slightly modified slides today.

Thanks
Rohit

**Comment by rohit-walimbe** [comment]
[ML with scikit-learn_rohit-walimbe.pdf](https://github.com/pythonpune/meetup-talks/files/3858362/ML.with.scikit-learn_rohit-walimbe.pdf)

[scikitlearn_demo_python_pune.ipynb.zip](https://github.com/pythonpune/meetup-talks/files/3858380/scikitlearn_demo_python_pune.ipynb.zip)

**Comment by bhavin192** [comment]
Fixed by #72
