### ISSUE TITLE
Demystifying Chatbots

### ISSUE THREAD

**Issue by celiberate** [pythonpune/meetup-talks#63]
**Title of the talk**
Demystifying Chatbots

**Description**
The session will cover
1. Introduction to Chatbots & Recent Trends
2. Chatbot Internals - What goes behind the scenes
- Intent Classification
- Named Entity Recognition
- Dialogue Tracker
3. Measure accuracy of your chatbot
4. Key Challenges & Considerations
5. Open Source Frameworks for building Chatbots
6. Q&A

**Duration (including Q&A)**
30-45 mins

**Prerequisites**
Interest in Natural Language Processing, Basics of Machine Learning

**Comment by bhavin192** [comment]
Hey @celiberate, thank you for the proposal. Will you be able to deliver this talk during this month's meetup which is on 17th? https://www.meetup.com/PythonPune/events/266249968/

**Comment by celiberate** [comment]
yes..This is for 17th session only.

Thanks,
Shivam

**Comment by bhavin192** [comment]
This talk has been scheduled here https://www.meetup.com/PythonPune/events/266249968/

See you in the meeup.

**Comment by bhavin192** [comment]
I was really nice talk. Can you please share link to the slides? Also is it fine if we upload the recording of your talk to our YouTube channel with CC-BY-SA 4.0 licence?

**Comment by celiberate** [comment]
yes. Please go ahead. You need the slides?

**Comment by bhavin192** [comment]
Yep, will be awesome to have link to the slides, so that we can add them to summary page as well as video description.

**Comment by celiberate** [comment]
[demystifying-chatbots.pdf](https://github.com/pythonpune/meetup-talks/files/3859344/demystifying-chatbots.pdf)
