### ISSUE TITLE
Friendly Introduction to Machine Learning

### ISSUE THREAD

**Issue by santoshvijapure** [pythonpune/meetup-talks#65]
**Title of the talk**
Friendly Introduction to Machine Learning 
**Description**
I'll cover the following points

- machine-learning introduction

- Why do we need to learn Machine Learning?

- how ML is different from traditional programming

- What Can ML Do  

- Real-world use cases

- AI vs ML vs DL

- a simple overview of the following algorithms : 

   1. Classification
   2. Regression
    3. Clustering
    4. Sequence Prediction
    5. Style Transfer

-Q&A

**Duration (including Q&A)**
30-40 minutes 

**Prerequisites**
Interest in AI/ML

**Comment by bhavin192** [comment]
Hey @santoshvijapure, thank you for the proposal. Will you be able to deliver this talk in this months meetup which is on 17th? https://www.meetup.com/PythonPune/events/266249968/

**Comment by santoshvijapure** [comment]
yes sure.
it'll be my first meetup talk  : )
Thanx

**Comment by santoshvijapure** [comment]
for certificate: bit.ly/pyPune

**Comment by bhavin192** [comment]
Hey @santoshvijapure can you please share the slides if possible?
