### ISSUE TITLE
December 2019 PythonPune Newsletter Collection Box 

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#67]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during November pythonpune meetup. 

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this. 

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
Fastest Way to Load Data Into PostgreSQL Using Python - https://hakibenita.com/fast-load-data-python-postgresql

**Comment by raukadah** [comment]
PyCon India 2019 videos: https://www.youtube.com/playlist?list=PL6GW05BfqWIfsflQt05LM3FTX6cd7PGps

**Comment by raukadah** [comment]
"Writing a PEG parser for fun and profit" - Guido van Rossum (North Bay Python 2019) - https://www.youtube.com/watch?v=QppWTvh7_sI&feature=youtu.be

**Comment by raukadah** [comment]
Python built-ins worth learning : https://treyhunner.com/2019/05/python-builtins-worth-learning/

**Comment by raukadah** [comment]
The return of Python dictionary "addition" - https://lwn.net/Articles/803189/

**Comment by raukadah** [comment]
Programmers are humans too: On the design of notations : https://homepages.cwi.nl/~steven/Talks/2019/11-21-dijkstra/

**Comment by sourabhdeshmukh** [comment]
http://pythontutor.com/visualize.html#mode=edit 
Best step by step explanatory IDE to get visualization of execution of python program.

**Comment by sourabhdeshmukh** [comment]
https://pythonbytes.fm/
Python Bytes is a weekly podcast hosted by Michael Kennedy and Brian Okken. Python Bytes podcast delivers headlines directly to your earbuds. If you want to stay up on the Python developer news but don't have time to scour reddit, twitter, and other news sources, just subscribe and you'll get the best picks delivered weekly

**Comment by sourabhdeshmukh** [comment]
https://twistedmatrix.com/trac/
Twisted is an event-driven networking engine written in Python and licensed under the open source ​MIT license. Twisted runs on Python 2 and an ever growing subset also works with Python 3.

**Comment by raukadah** [comment]
The Mind at Work: Guido van Rossum on how Python makes thinking in code easier - https://blog.dropbox.com/topics/work-culture/-the-mind-at-work--guido-van-rossum-on-how-python-makes-thinking

**Comment by raukadah** [comment]
https://conf.kde.in/ and https://nullcon.net/website/

**Comment by raukadah** [comment]
Craft Your Python Like Poetry - https://treyhunner.com/2017/07/craft-your-python-like-poetry/

**Comment by raukadah** [comment]
https://www.paramiko.org/changelog.html#2.7.0

**Comment by raukadah** [comment]
Refactoring Python Applications for Simplicity https://realpython.com/python-refactoring/#using-rope-for-refactoring

**Comment by raukadah** [comment]
Circuit Python at PyConf Hyderabad https://anweshadas.in/circuit-python-at-pyconf-hyd/
