### ISSUE TITLE
Hands on chatbot developement on Rasa using Zomato API

### ISSUE THREAD

**Issue by harinjoshi** [pythonpune/meetup-talks#73]
**Title of the talk**
Hands on chat-bot developement using Zomato API

**Description**
Co-learning lounge is Hyderabad based AI community which aims at educating students through free workshops.We Successfully conducted events in Mumbai,New Delhi,Hyderabad,Bangalore,Mathura and we would like to conduct one in Pune.
This workshop will cover all aspects of chat-bot right from its evaluation to present scenario in market to future prospects.
This Workshop will be hands-on development of chatbot using Rasa framework.

**Duration (including Q&A)**
4 hours

**Prerequisites**
Everyone must be aware of Object-oriented Python
Laptop with charger is must.
Everyone will be provided with setup instructions a day before workshop.

**Comment by bhavin192** [comment]
Hello @harinjoshi! that is indeed an exciting proposal! First of all sorry for a really delayed response. Will you be able to deliver this in next month? Can you please reach out over punepython at gmail dot com, so that we can discuss it further.

**Comment by harinjoshi** [comment]
Yes,sure @bhavin192. Is mail id punepython@gmail.com?

**Comment by bhavin192** [comment]
Yes, that's correct.

**Comment by harinjoshi** [comment]
Can I get on call with any of python pune person??

**Comment by bhavin192** [comment]
Please add your contact details to the same email thread we have.

Also, this workshop is scheduled as this month's meetup. 

As discussed over email, the workshop will start around 10:00, 10:30. We have set the time as 9:00 to make sure everyone has the required setup on their machine.

**Comment by DilipThosarGithub** [comment]
"Everyone will be provided with setup instructions a day before workshop."
Awaiting...

**Comment by bhavin192** [comment]
Hey @DilipThosarGithub, did you register on the Google forms link given in the meetup event?

**Comment by bhavin192** [comment]
Hello @harinjoshi can you please share link to the slides as well?
