### ISSUE TITLE
December PythonPune DevSprint Ideas

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#75]
## Goal
Let's learn something new today

## What we are going to do today?
Pick any project, build, explore and break it and propose the fix.

## Projects to check out
* Python 3.8.1 rc1 -> https://www.python.org/downloads/release/python-381rc1/
* Linkstatus -> https://github.com/pythonpune/linkstatus
* bot-irc -> https://github.com/pythonpune/bot-irc

## I want to work on new or existing project, what to do?
Add the project in github issue comment.

## I donot know Python, What should I do?
Take a look at following books and find a pythonists and learn together
* Python for you and me - https://pymbook.readthedocs.io/en/latest/
* Think Python - http://greenteapress.com/thinkpython2/html/index.html

**Comment by chavarera** [comment]
Project Name: **CInfo (Computer Information)**

Platform: **Linux and windows**

Github link: https://github.com/chavarera/Cinfo/

CInfo Gathers Following Information for Windows and Linux platform and use it for auditing purpose .
```
System Information
Network Information
Software Information
Storage Information
Hardware Information
File Information
And more information coming soon
and help you to export into text file.
```
You can contribute anything related to this domain

**Comment by raukadah** [comment]
https://github.com/GetTogetherComm/GetTogether

**Comment by Akasurde** [comment]
Ansible EasyFixes - https://github.com/ansible/community/issues/437

**Comment by digitronik** [comment]
@chavarera can you please ping me on `irc` or `telegram` my nik is `digitronik`
