### ISSUE TITLE
January 2020 PythonPune Newsletter Collection Box 

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#76]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during November pythonpune meetup. 

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this. 

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
A Tiny Python Exception Oddity  https://aroberge.blogspot.com/2019/12/a-tiny-python-exception-oddity.html?m=1

**Comment by raukadah** [comment]
https://www.python.org/dev/peps/pep-8101/#results - 
PEP 8101 -- 2020 Term steering council election

**Comment by raukadah** [comment]
What makes Python a great language? https://stevedower.id.au/blog/python-a-great-language/

**Comment by raukadah** [comment]
Usenix ;login: Python Column - https://www.dabeaz.com/usenix.html

**Comment by chavarera** [comment]
Google summer of code 2020 program timeline announced 
https://summerofcode.withgoogle.com/how-it-works/#timeline

**Comment by amolkahat** [comment]
Get awesomeness https://docs.openstack.org/tripleo-quickstart/latest/getting-started.html
To retrieve all amazing awesomeness from Github

**Comment by amolkahat** [comment]
https://free-for.dev/
Developers and Open Source authors now have a massive amount of services offering free tiers, but it can be hard to find them all in order to make informed decisions.

**Comment by girish946** [comment]
PyPy 7.3.0 released 
The version 7.3.0 of PyPy, includes two different interpreters:

    PyPy2.7, which is an interpreter supporting the syntax and the features of Python 2.7 including the stdlib for CPython 2.7.13
    PyPy3.6: which is an interpreter supporting the syntax and the features of Python 3.6, including the stdlib for CPython 3.6.9.

https://morepypy.blogspot.com/2019/12/pypy-730-released.html

**Comment by raukadah** [comment]
Creator of Python Programming Language, Guido van Rossum | Oxford Union - https://www.youtube.com/watch?v=7kn7NtlV6g0

**Comment by raukadah** [comment]
Python 3.7 Development Mode - https://vstinner.github.io/python37-dev-mode.html

**Comment by raukadah** [comment]
Mercurial's Journey to and Reflections on Python 3 - https://gregoryszorc.com/blog/2020/01/13/mercurial%27s-journey-to-and-reflections-on-python-3/

**Comment by raukadah** [comment]
Start using 2FA and API tokens on PyPI  - http://pyfound.blogspot.com/2020/01/start-using-2fa-and-api-tokens-on-pypi.html

**Comment by raukadah** [comment]
A Book about Pythonic Application Architecture Patterns for Managing Complexity - https://github.com/cosmicpython/book#table-of-contents

**Comment by raukadah** [comment]
Better Python Object Serialization - https://hynek.me/articles/serialization/

**Comment by raukadah** [comment]
I'm not feeling the async pressure - https://lucumr.pocoo.org/2020/1/1/async-pressure/

**Comment by digitronik** [comment]
publish
https://github.com/pythonpune/meetup-talks/pull/78
