### ISSUE TITLE
[Dev Sprint] Genpass -  Command Line Password manager tool.

### ISSUE THREAD

**Issue by mayurilahane** [pythonpune/meetup-talks#77]
**Title: [Dev Sprint] Genpass -  Command Line Password manager tool.**

**Description**
- https://github.com/paint-it/genpass
- This tool used to create a new password(using diceware API) and to save the existing passwords.
- Advanced features like security of tool, password encryption, etc. will be introduced in the next releases. 
- Now we have the first release(v0.0.1). It supports saving the existing password and creating new passwords with respect to particular portal names.

**What are we expecting?**
- Looking for contributions in terms of code, docs, ideas/suggestions, etc.
- Deploy initial release on PyPI

**Prerequisites**
- Basic Python Programming
- Basic knowledge of Git and GitHub is required to contribute or work on this project

**Comment by bhavin192** [comment]
@mayurilahane thank you for submitting a detailed proposal! This has been scheduled in this month's meetup (Talk + devsprint)

**Comment by raukadah** [comment]
@mayurilahane Please share the slides link.

**Comment by mayurilahane** [comment]
Thanks **Python Pune team** for the support and this opportunity!
here is the link for slides - https://gist.github.com/mayurilahane/31f0c97a5875c44f73f62010a8be43d2
