### ISSUE TITLE
February 2020 PythonPune Newsletter Collection Box 

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#79]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during February pythonpune meetup. 

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this. 

## How to add new package release:
Paste the link of new package release

## How to include events here:
if a new event is happening in Pune and want to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
https://realpython.com/python-boto3-aws-s3/ - Python, Boto3, and AWS S3: Demystified

**Comment by raukadah** [comment]
python 3.9 compatibility changes - https://tirkarthi.github.io/programming/2020/01/27/python-39-changes.html

**Comment by raukadah** [comment]
https://github.com/asottile/pyupgrade - 
A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.

**Comment by raukadah** [comment]
https://github.com/rednafi/py-sanity - 
Opinionated coding guidelines and best practices in Python

**Comment by raukadah** [comment]
Anthony Shaw - Wily Python: Writing simpler and more maintainable Python - PyCon 2019 - https://www.youtube.com/watch?v=dqdsNoApJ80

**Comment by raukadah** [comment]
https://pythonspeed.com/articles/alpine-docker-python/ - Alpine makes Python Docker builds 50× slower, and images 2× larger

**Comment by raukadah** [comment]
Reducing Startup Time of Python Applications - https://engineering.algoshelf.com/python-startup-time/

**Comment by Pradhvan** [comment]
Django async view support - https://forum.djangoproject.com/t/async-performance/310/6 

Announcement tweet by Andrew Godwin - https://twitter.com/andrewgodwin/status/1222214836043468800

**Comment by raukadah** [comment]
The Mental Game of Python - Raymond Hettinger - https://www.youtube.com/watch?v=UANN2Eu6ZnM

**Comment by raukadah** [comment]
View and control unix terminals from your browser https://cs01.github.io/termpair/

**Comment by Pradhvan** [comment]
[The 22 Most-Used Python Packages in the World](https://medium.com/better-programming/the-22-most-used-python-packages-in-the-world-7020a904b2e)

**Comment by Pradhvan** [comment]
[Growing Old Gracefully as a Programmer](https://djangochat.com/episodes/growing-old-gracefully-as-a-programmer) ~ 30.32 min

**Comment by raukadah** [comment]
How key Python projects are maintained- https://opensource.com/article/20/2/python-maintained
