### ISSUE TITLE
March 2020 PythonPune Newsletter Collection Box

### ISSUE THREAD

**Issue by digitronik** [pythonpune/meetup-talks#81]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during **March PythonPune** meetup. 

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this. 

## How to add new package release:
Paste the link of new package release

## How to include events here:
If a new event is happening in Pune and wants to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
sys.getsizeof is not what you want - https://nedbatchelder.com/blog/202002/sysgetsizeof_is_not_what_you_want.html

**Comment by raukadah** [comment]
Contributing to CPython - https://paper.dropbox.com/doc/Contributing-to-CPython-JlgnduI6kw9MJIaGPpN9G

**Comment by raukadah** [comment]
Ever had a cool idea for an Open Source project but didn't have the time to implement it yourself? Let someone else give it a try! https://open-source-ideas.github.io/

**Comment by Pradhvan** [comment]
Your Guide to the CPython Source Code: https://realpython.com/cpython-source-code-guide/

**Comment by girish946** [comment]
Applying mypy to real world projects: http://calpaterson.com/mypy-hints.html

**Comment by raukadah** [comment]
Cheating in Kaggle Contests (A Post-Mortem) - https://www.kaggle.com/bminixhofer/how-bestpetting-cheated

**Comment by raukadah** [comment]
OSCON 2019 - Care and Feeding of a Healthy Job Hunt - https://archive.org/details/oscon2019-jobhunt

**Comment by raukadah** [comment]
Git Command Explorer - https://gitexplorer.com/

**Comment by raukadah** [comment]
https://pypi.org/project/Automat/20.2.0/ - Self-service finite-state machines for the programmer on the go.

**Comment by raukadah** [comment]
About Python Package Metadata - https://hynek.micro.blog/2020/02/14/about-python-package.html

**Comment by raukadah** [comment]
Modularity for Maintenance - https://glyph.twistedmatrix.com/2020/02/modules-for-maintenance.html

**Comment by chavarera** [comment]
Visualising Data Structures and algorithms through animations
https://visualgo.net/en

**Comment by Pradhvan** [comment]
PEP 614 -- Relaxing Grammar Restrictions On Decorators - https://www.python.org/dev/peps/pep-0614/

**Comment by raukadah** [comment]
Layoffs are Coming -  https://jacobian.org/2020/mar/13/layoffs-are-coming/

**Comment by raukadah** [comment]
Click 7.1 Released - https://palletsprojects.com/blog/click-7-1-released/

**Comment by raukadah** [comment]
Python in GitHub Actions - https://hynek.me/articles/python-github-actions/

**Comment by raukadah** [comment]
Python in Production - https://hynek.me/articles/python-in-production/

**Comment by raukadah** [comment]
Virtual Ansible Contributor Summit + Hackathon - Sunday, March 29, 2020! - https://groups.google.com/forum/#!topic/ansible-outreach/iYFoB9g3cSE

**Comment by Pradhvan** [comment]
Closes #88

**Comment by bhavin192** [comment]
Closing this as #88 is merged now.
