### ISSUE TITLE
Design Patterns and Python: Creational Patterns

### ISSUE THREAD

**Issue by aprajshekhar** [pythonpune/meetup-talks#82]
**Title of the talk**
Design Patterns and Python: Creational Patterns

**Description**
Design patterns help in developing robust, and maintainable applications. My talk discusses the following two main creational patterns and how to implement them in Python:

- Singleton
- Factory

**Duration (including Q&A)**
45 mins to 1 hour

**Prerequisites**
Basic knowledge of python

Note: It would be great if this scheduled when meet is happening near Magrapatta.

**Comment by bhavin192** [comment]
Hello @aprajshekhar thank you for proposing this talk, it's indeed an interesting topic. Will you be able to deliver this on 21st March? Meetup will be happening either near Magarpatta or virtually (using Jitsi Meet) or both.

**Comment by aprajshekhar** [comment]
@bhavin192 sorry for the late reply. Yes 21st will be perfect.

**Comment by bhavin192** [comment]
No worries. This talk has been scheduled in this month's meetup. https://www.meetup.com/PythonPune/events/269419831/

**Comment by bhavin192** [comment]
Hello @aprajshekhar can you please share link to your slides so that I can include that in the event summary. Also we look forward to your future talks :smile:

**Comment by aprajshekhar** [comment]
Hi @bhavin192 following is the link to the slides:
https://docs.google.com/presentation/d/1ThuWxvc93gaJg1060dB6p83-gMpz4aCR_Mi5REHa9MI/edit?usp=sharing

Thanks and looking forward to giving talks in the future :)
