### ISSUE TITLE
Using Pipeline scripts in Jenkins

### ISSUE THREAD

**Issue by vipin3699** [pythonpune/meetup-talks#86]
#### Title of the talk
Automation with Jenkins

#### Description
This talk is about, What is Jenkins and how we can use it to automate different tests with different scenarios using Jenkins pipeline.

#### Duration (including Q&A)
30-45 minutes

#### Checklist

The talk/workshop speaker agrees to,
- [x ] Share the slides, code snippets and other material used during the talk
- [x ] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [x ] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
This talk has been scheduled in this month's meetup. https://www.meetup.com/PythonPune/events/269419831/
