### ISSUE TITLE
Time Complexity: Comparing C++(vector) and Python(list)

### ISSUE THREAD

**Issue by amitkumar50** [pythonpune/meetup-talks#87]
#### Title of the talk
Comparing C++(vector) and Python(list)

#### Description
Finding Lucky number using:
1. C++(vector)
2. Python(list)
Calculating the runtime for both algos.

What is lucky number?
Lucky number?A element of matrix such that it is minimum element in its row and maximum in its column.

Input: matrix = [[3,7,8],[9,11,13],[15,16,17]]
Output: [15]
Explanation: 15 is the only lucky number since it is the minimum in its row and the maximum in its column

Input: matrix = [[7,8],[1,2]]
Output: [7]

#### Duration (including Q&A)
45 minutes

#### Prerequisites

Should be aware about C++(2 D vector), Python(2 D list)

#### Checklist

The talk/workshop speaker agrees to,
- [y ] Share the slides, code snippets and other material used during the talk
- [y ] If the talk is recorded, you grant the permission to release the video on [PythonPune's YouTube channel](https://www.youtube.com/channel/UCWjk7oGWV9eknuOzC20dyiQ) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [ y] Not do any hiring pitches during the talk and follow the [Code of Conduct](https://github.com/pythonpune/meetup-talks#code-of-conduct)

**Comment by bhavin192** [comment]
Hey @amitkumar50 thank you for submitting an interesting proposal! Will you be able to deliver this during this month's meetup which is on 18th April (Saturday). It will be an online event.

**Comment by amitkumar50** [comment]
@bhavin192 Sure I can deliver what will be time of talk and duration?

**Comment by bhavin192** [comment]
We will be starting around 10:30AM on 18th April. Duration for your talk will be 45 minutes (according to your proposal).

**Comment by bhavin192** [comment]
@amitkumar50 sorry for a last minute change, the date has been finalized as 26th April, Sunday. Hope that works for you!

**Comment by amitkumar50** [comment]
@bhavin192 Sure no problem I am good with 26th april

**Comment by amitkumar50** [comment]
@bhavin192 And Thank you very Much for considering my talk I am obliged. I will send the slides maybe by Thursday for your review

**Comment by bhavin192** [comment]
It's our pleasure to have you @amitkumar50, our aim is to create a platform for all the Pythonistas around (but not limited to) Pune. Would love to review the slides as well. This talk has been scheduled here, https://www.meetup.com/PythonPune/events/270019437/

**Comment by amitkumar50** [comment]
Apologies for delay!
presentation.
[vector-vs-lists.pptx](https://github.com/pythonpune/meetup-talks/files/4532614/vector-vs-lists.pptx)
