### ISSUE TITLE
[Proposal] Presenter should specify talk category in talk proposal

### ISSUE THREAD

**Issue by Yadnyawalkya** [pythonpune/meetup-talks#97]
#### Suggestion
- Presenter should choose appropriate talk category suitable for talk. Not more than 3 categories, if presenter do not find relevant category, we can keep it under "others". 
**Action item if the proposal is accepted** -  Add instructions into [issue template](https://github.com/pythonpune/meetup-talks/blob/master/.github/ISSUE_TEMPLATE/propose-a-talk.md) and specify example categories.
	- Community
	- Developer Tools
	- Documentation
	- DevOps / Cloud and Containers / Virtualization / Microservices
	- Frontend / UI / UX
	- IoT
	- Kernel / Operating System
	- ML / AI / Big Data
	- Networking
	- Programming / Debug
	- Quality / Testing
	- Security
	- Storage
	- Popular thrends
	- Others

- Should have landing page in which we can tag all talks by their category (something similar to this index and data structures categorization - https://github.com/jwasham/coding-interview-university#table-of-contents)
**Action item if the proposal is accepted** - Need to create landing page with index/anchor hooks or need to think on better solution.

#### But why?
To keep track of all talks for future references. And also it can reduce chances of having duplicates talks (presenter can refer previous talk list according to category).

#### Then whats wrong with past event summary and newsletter?
Nothing wrong as such. Just digging for old talk could be hard. Yes, you search specific talks with GitHub search-bar but what if I just want get list of all talks on "Security" category, this is not possible right now.

**Comment by bhavin192** [comment]
Yes, you are right. We have a task of creating site here https://pythonpune.in . Plan is to have the meetup summary and newletter there as posts. 

It will be good if we ask for the category. My intention was to keep things minimum so that it's less friction for submitting a new talk. One thing we can do is, have fixed set of categories and add those while creating the summaries of past meetups, what do you think? That way we can skip asking the category to speakers.

**Comment by Yadnyawalkya** [comment]
Ack on upcoming task. Yeah, tagging it while creating summaries also make sense. Closing this issue in favor of that. 

Putting everyone FYI. @raukadah @digitronik @vishal-vvr @akshay196
