### ISSUE TITLE
May 2020 PythonPune Newsletter Collection Box

### ISSUE THREAD

**Issue by raukadah** [pythonpune/meetup-talks#98]
Let's use this issue to collect python related news, new package updates and events happening around Pune. We can compile and publish it during **May PythonPune** meetup. 

## How to add news:
Comment on this issue with news link and news topic and also include the source from we got this. 

## How to add new package release:
Paste the link of new package release

## How to include events here:
If a new event is happening in Pune and wants to share in the newsletter, feel free to drop the event link with date and venue.

**Comment by raukadah** [comment]
Calling all Pythonistas in the world, Call for Proposals for PyCon India 2020 is now open! https://in.pycon.org/blog/2020/2020-call-for-proposals-announcement.html
Notes:
* CFP last date is 14th August 2020
* You can submit the talks here: https://in.pycon.org/cfp/2020/proposals/
* Have queries ping on https://pyconindia.zulipchat.com/

**Comment by raukadah** [comment]
https://pypistats.org/ - Analytics for PyPI packages
Notes:
* You can find your python package download stats.

**Comment by raukadah** [comment]
Test pip’s alpha resolver and help us document dependency conflicts -
http://www.ei8fdb.org/thoughts/2020/05/test-pips-alpha-resolver-and-help-us-document-dependency-conflicts/

Notes:
* Needs feedback on the work on improving the way that pip resolves package dependency conflicts 
* If your's project having 10 package dependencies, packages pinned to specific version then try out
* Install pip install —upgrade —pre pip to get latest pip
* Install the project using --unstable-feature=resolver
* And then submit feedback

**Comment by raukadah** [comment]
Project Twint: https://github.com/twintproject/twint
Notes:
* An advanced Twitter scraping tool which does not uses twitter API
* Install it via pip3 install twint in a virtualenv
* To get all tweets of a user, Run twint -u <twiteer username>

**Comment by Pradhvan** [comment]
The _practical Python course_ from David Beazley is released under a Creative Commons license.
https://dabeaz-course.github.io/practical-python/

Note:
* Students of this course are usually professional scientists, engineers, and programmers who already have experience in at least one other programming language.  
* The course includes the completion of approximately 130 hands-on coding exercises.

**Comment by raukadah** [comment]
https://www.jetbrains.com/lp/python-developers-survey-2019/
Jet Brain's survey. Every year they conduct this survey. This survey is based on the Python and it's toolchanin. It's representation is in the graphs. And they conducted survey with most interesting topics.
- Python as main vs secondary language
- For what purpose mainly do you use python?
- Which python versions you use most? and etc.

**Comment by raukadah** [comment]
https://lwn.net/Articles/819853/

This article desribe about the Python3.9 PEPs. What peps are proposed or new changes coming in to Python 3.9. It include some examples of the String manipulation, new parser etc.

**Comment by raukadah** [comment]
https://kushaldas.in/posts/single-file-implementation-of-pep582.html
Notes:
* To help beginners in writing Python effectively without going through complexity of virtual envs.
* python3 pep582.py --install
* Make __pypackages__ directory
* python3 -m pip install attrs
* Open python3 prompt and import attrs

https://opensource.com/article/20/5/pycon-covid-19
* Thanks to Python community, US PyCon 2020 happened
* The impact on PSF employees and event cancellations

https://hynek.me/articles/waiting-in-asyncio/
* It takes about different asyncio keywords and 
* using Python’s asyncio is being able to fire off many coroutines and run them concurrently. How many ways do you know for waiting for their results?

https://www.pythonmorsels.com/topics/duck-typing/
* An idea where we donot check the type of something in python but what the behaviours it support
* It captures duck typing examples based on behaviour driven nouns.

http://whereistejas.me/2020/05/26/Double-Pendulum-Part-1.html
A series about  animate stuff using python’s matplotlib library

**Comment by raukadah** [comment]
New releases:
* https://github.com/pypa/pipenv/releases/tag/v2020.5.28
* Python 3.9.0b1 is now available for testing https://blog.python.org/2020/05/python-390b1-is-now-available-for.html

*New Projects to try:
https://github.com/dry-python/returns
